**General note**: Each notebook consists of a cells. A cell is a unit that includes either code or a text. Code cells are responsible for programming part, while text cells helps us to structure our scripts and comment the code. We can use markup language to increase readibility of text cells. It also allows us to define headings to distinguish between different topics in our script.

*Markup language - selected features:*

|Effect|How to|
|:------|------|
|header level 1|\#|
|header level 2|\#\#|
|highlight text|\`|
|bold text|\*\*|
|italic text|\*|
|hyperlink|<a href="https:\\www2.karlin.mff.cuni.cz/~kpms/" target="_blank">go to kpms web </a> |
|image|<img src="https://i.pinimg.com/564x/2f/9c/11/2f9c11f9e55efbf1791f12c06d60729b.jpg" width=100px style="float: left"/>|


You can also use <a href="https:\\github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank"> Markdown Cheatsheet </a>

# Download data

Download the data from <a href="https://www2.karlin.mff.cuni.cz/~kozmikk/files/data_devsample.zip" target="_blank">credit risk data</a> and unpack it to the Data folder.

# Basic syntax

<span style="color:red">**TO DO:** Create a markup cell 1.1 Data types in Python, listing the build-in data types in the cell below</span>

hint: bullets can be created using `-`

str: text
int, float, comlex: numeric types
list, tuple, range: sequence types
dict: mapping type
set, frozenset: set types
bool: boolean type
bytes, bytearray, memoryview: binary types

**General note:** When we run a cell the code is executed. if the last line of the code contains an output, this output is displayed automatically. If we want to display something at the middle of the code, we can use function `print`.

In [1]:
# function type return data type of a variable
type("Hello")
type(1)

int

**General note**: Inside code cell, any line that begins with `#` is considered to be a comment.

### Strings
- String is a data type used for texts of variable lengths
- Strings are defined either by `"` or `'`
- Multiline string can be defined by using `"""` or `'''`
- Escape characters can be used to format a text

In [ ]:
# create a variable of string data type
first_string = 'There can be any text.'
# print the content of the variable
first_string

<span style="color:red">**TO DO:** Save following string to variable and print it: `I'm the string with apostrophe.`</span>

In [ ]:
# we can use either " or ' - both have the same meaning in python
second_string = "There can be any text."

first_string == second_string

In [ ]:
# Multiline string
multiline_string = """
This text is 
written on multyple 
lines.
"""

print(multiline_string)
multiline_string

**General note:** A text can be formatted using escape sequence characters. In example above, escape sequence `\n` was used to mark new line. Note that function `print` processes escape sequences (they are replaced by their meaning during printing the text).

Selected escape sequence characters:

|Escape sequence|Meaning|
|:---------------|-------|
|\n|new line|
|\t|tab|
|\\\\|print backslash|
|\\'|print single quote|
|\\"|print double quote|

In [ ]:
# use escape sequence to print multiline string
print('first line \nsecond line \nthird line')

In [ ]:
# we can use escape sequence for instance to print quotes
string_with_quotes = 'this string has \'single quotes\' inside'
print(string_with_quotes)

#if we combine single and double quotes, we don't need to use escape sequence
string_with_quotes = 'when combining \'SINGLE\' and "DOUBLE" quotes, we don\'t need to use escape sequence' 
print(string_with_quotes)

#### Uperrcase and lowercase

In [ ]:
# Strings have method lower() and upper()
print(string_with_quotes.upper())
print(string_with_quotes.lower())

#### String subsetting
- To subset a string, use `[first_character: last_character]` after the string variable - note that first_character is included, while last_character is not
- Method `replace()` can be used to replace part of the string

**General note:** !!! Python indexes positions from 0 !!!

In [ ]:
string = 'Matfyz is the best university in the world.'

# first character
print(string[0])

# last character
print(string[-1])

# first 3 characters
print(string[0:3])
# this is equal to 
print(string[:3])

# last 3 characters
print(string[-3:])

# middle of the sentence
print(string[5:10])

# we can do...
print(string[:1000])
# ...and also we can...
print(string[1000:10000])
# ...but we cannot do
print(string[1000])

#### Replace substring

In [ ]:
# replace substring
modified_string = string.replace('world', 'galaxy')
modified_string

<span style="color:red">**TO DO:** Change Matfyz to Charles University by using string replacement.</span>

In [ ]:
correct_string = 
correct_string

#### String concatenation

In [ ]:
concatenated_string = correct_string + ' ' + string.replace('university', 'faculty')
print(concatenated_string)

#### Variables inside string
- We have three options:
    1. % syntax (borrowed from C)
    2. `format()` method
    3. f-string

In [ ]:
constant = 'pi'
value = 3.141592

# % syntax
print('%s = %f' % (constant, value))

# format() method
print('{} = {}'.format(constant, value))

# f-string
print(f'{constant} = {value}')

# number formats
print(f'{constant} = {value:.2f}')
print('{} != {:,.0f}'.format(constant, value*1000).replace(',', ' '))

<span style="color:red">**TO DO:** Print result of varible `num` in following format: <br></span>
- thousands separator = '(space)'<br>
- 3 decimal numbers

In [ ]:
num = 123456.789101112

#### Split and join

In [ ]:
# split text by space
splited_text = correct_string.split(' ')
print(splited_text)

# join text using underscore
joined_text = '_'.join(splited_text)
print(joined_text)

#### Find substring

In [ ]:
string = 'Matfyz is the best university in the world.'

# find location of school
idx = string.find('university')
print(f'Word "school" starts at position:   {idx}')

<span style="color:red">**TO DO:** Find location of word `best` and replace it by `worst`.<br></span>
- Don't use `replace`!

In [ ]:
new_string =

**General note:** To see function implementation details, we can use ? or ?? operator. ? returns docstring for given function/method, while ?? returns full code with implementation.

In [ ]:
?string.find

#### Colored text
- Colored text is implemented in package termcolor

In [ ]:
from termcolor import colored

# color Matfyz with red
print(colored('Matfyz', 'red') + ' is the best university in the world.')

### Numeric types

#### Integer

In [ ]:
# integer / integer returns ???
print(f'1 / 1 = {1 / 1}')

In [ ]:
# what will happen if we divide by 0?
print(f'1 / 0 = {1 / 0}')

#### Float

In [ ]:
pi = 3.141592

# floats can be rounded
print(f'Rounded decimal number:   {round(pi, 2)}')

inf = float('inf')
print(f'1 / inf = {1 / inf}')
print(f'inf / inf = {inf / inf}')

nan = float('nan')
print(f'nan * 10 = {nan * 10}')
print(f'nan * inf = {nan * inf}')

In [ ]:
# float can be converted to int and vice versa. When converting float to int, decimal part is removed
e = 2.71828
print(f'Rounded e:            {round(e)}')
print(f'e converted to int:   {int(e)}')
print(f'e to int to float:    {float(int(e))}')

#### Complex numbers

In [ ]:
import cmath

complex_number = complex(-1, 0)
print(f'Square root of -1+0j:   {cmath.sqrt(complex_number)}')

complex_number = complex(0, 1)
print(f'j squared:              {complex_number * complex_number}')

### Sequences

#### List
- List is a collection of ordered and changeable items
- List can consists of items of different data types
- List is defined using []

In [ ]:
basic_list = [
    3.14,
    2.71,
    6.62
]

print(basic_list)

# Lists are ordered - each item has a possition that is fixed
print([basic_list[1], basic_list[2], basic_list[0]])

# Lists are changeable -> we can change list's item values
basic_list[2] = 1.60
print(basic_list)

In [ ]:
# Lists can be subseted similarly as strings
print(basic_list[1:])

In [ ]:
# list can containt different data types
list_with_multiple_types = [
    3.14,
    'Hello',
    12,
    complex(-1,0)
]

print(list_with_multiple_types)

In [ ]:
# sorting a list
sorted(basic_list, reverse = False)

In [ ]:
# multiplying a list
basic_list * 2

In [ ]:
# appending to list
basic_list.append(6.62)
basic_list

In [ ]:
# extending a list
basic_list.extend([0, 1, 2, 3])
basic_list

In [ ]:
# numerical lists can be sumed (other operations)
sum(basic_list)

<span style="color:red">**TO DO:** Print random text and below print underscores, so that text is undelined.</span>
- Result should look like this:

Some random text<br>
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-

#### Tuple
- Tuple is a collection of ordered but unchangable items
- Tuple is defined using ()

In [ ]:
basic_tuple = (
    3.14,
    2.71,
    6.62
)

print(basic_tuple)

In [ ]:
# items of tuple cannot be changed
basic_tuple[2] = 1.6

In [ ]:
# tuple can be sorted in the same way as list -> note that returned value is list, not tuple
sorted(basic_tuple, reverse = True)

In [ ]:
# tuple and list can be combined
list_of_tuples = [
    ('pi', 3.14),
    ('euler', 2.17),
    ('planck', 6.62)
]

print(list_of_tuples)

# and we can sort such a structure for instance based on the second items of tuples
sorted(list_of_tuples , key=lambda tup: tup[1])

### Range
- range data type is used to generate arithmetic sequence of integers
- it is iterable -> more efficient when looping over a sequence

In [ ]:
range_variable = range(5)
print(range_variable)

In [ ]:
for i in range(5):
    print(i)
print()

for i in range(1, 5):
    print(i)
print()

for i in range(1, 5, 2):
    print(i)

In [ ]:
# range generates sequence with integer distances between items
range(1,5,0.5)

<span style="color:red">**TO DO:** Use `range` to calculate followin equation:</span>
$$\sum_{i=1}^{100} 5 * (i + 1)$$

### Dictionary
- Dictionary is unordered and indexed collection
- Duplicate items are not allowed
- Dictionary is defined using {}

In [5]:
for i in range(1,100) : 
    print((i+1)*5)

10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100
105
110
115
120
125
130
135
140
145
150
155
160
165
170
175
180
185
190
195
200
205
210
215
220
225
230
235
240
245
250
255
260
265
270
275
280
285
290
295
300
305
310
315
320
325
330
335
340
345
350
355
360
365
370
375
380
385
390
395
400
405
410
415
420
425
430
435
440
445
450
455
460
465
470
475
480
485
490
495
500

In [ ]:
basic_dictionary = {
    'one': 1,
    'two': 4,
    'three': 3,
    'two': 2
}

print(basic_dictionary)

In [ ]:
# get all keys in dictionary
print('Dictionary keys:          {}'.format(basic_dictionary.keys()))
print('Dictionary values:        {}'.format(basic_dictionary.values()))

print('Value of item \'one\' is:   {}'.format(basic_dictionary['one']))

In [ ]:
# sorting and indexing dictionary
sorted_dictionary = dict(sorted(basic_dictionary.items(), key=lambda item: item[1], reverse=True))
print(sorted_dictionary)

first_key = list(basic_dictionary)[0]
first_val = list(basic_dictionary.values())[0]

print(first_key)
print(first_val)

In [ ]:
# asking for non-existing key raises an error
basic_dictionary['four']

In [ ]:
# updating dictionary
basic_dictionary['one'] = -1
basic_dictionary['four'] = 4
print(basic_dictionary)

In [ ]:
# update = insert or rewrite
basic_dictionary.update({'five': 5, 'one': 1})
basic_dictionary

In [ ]:
# deleting an item
del basic_dictionary['two']
print(basic_dictionary)

In [ ]:
morse = {
    'A': '.-',
    'B': '-...', 
    'C': '-.-.',
    'D': '-..',
    'E': '.',
    'F': '..-.',
    'G': '--.',
    'H': '....',
    'I': '..',
    'J': '.---',
    'K': '-.-',
    'L': '.-..',
    'M': '--',
    'N': '-.',
    'O': '---',
    'P': '.--.',
    'Q': '--.-',
    'R': '.-.',
    'S': '...',
    'T': '-',
    'U': '..-',
    'V': '...-',
    'W': '.--',
    'X': '-..-',
    'Y': '-.--',
    'Z': '--..',
}

<span style="color:red">**TO DO:** convert string to morse code. Letters are separated by 'space', words by '|' and sentances are separated by '||'.</span>

In [ ]:
string = 'SOS. Calling for help.'

print()

### Set
- Unordered and unindexed collection
- Set is defined using {}
- Frozenset is the same as set only unchangable

In [ ]:
set_of_colors = {'red', 'green', 'blue'}
print(set_of_colors)

In [ ]:
reordered_set_of_colors = {'green', 'blue', 'red'}

# inside set, odrering is not important
set_of_colors == reordered_set_of_colors

In [ ]:
# adding one item
set_of_colors.add('yellow')
print(set_of_colors)

# adding multiple items
set_of_colors.update(['orange', 'purple'])
print(set_of_colors)

# remove one item
set_of_colors.discard('yellow')
print(set_of_colors)

#### Set operations
- Union
- Intersection
- Difference

In [ ]:
rgb_colors = {'red', 'green', 'blue'}
random_colors = {'red','cian', 'brown'}

# set union
union_colors = rgb_colors.union(random_colors)
print(f'Union of {rgb_colors} and {random_colors}:   {union_colors}')

# set intersection
set_intersection = rgb_colors.intersection(random_colors)
print(f'Intersection of {rgb_colors} and {random_colors}:   {set_intersection}')

# set complement
rgb_complement = rgb_colors.difference(random_colors)
print(f'Difference of {rgb_colors} and {random_colors}:   {rgb_complement}')

In [ ]:
# frozenset is unchangable -> we cannot add or remove items from frozenset
rgb_colors = frozenset(rgb_colors)
rgb_colors.add('yellow')

<span style="color:red">**TO DO:** Find values that are not in the intersection of sets.</span>

<img src="https://res.cloudinary.com/practicaldev/image/fetch/s--Kuq7OH5V--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://thepracticaldev.s3.amazonaws.com/i/eq8zrfkbs9jntiimwjk9.png" width=300px style="float: left"/>

In [ ]:
A = {0, 1, 2, 3, 4, 5, 6, 7}
B = {4, 5, 6, 7, 8, 9, 10, 11}

### Boolean
- Boolean values are either True or False
- We can do logic operations with boolean

In [ ]:
true = True
false = False

# logic operations
print(f'True and True = {true and true}')
print(f'True and False = {true and false}')
print(f'True or False = {true or false}')
print(f'Negation of True = {not true}')

In [ ]:
# boolean is an output of comparisons
print(f'1 = 1:   {1 == 1}')
print(f'1 = 2:   {1 == 2}')
print(f'1 > 2:   {1 > 2}')

## Operators in Python
- Arithmetic operators:

|Operator|Name|Example|
|:--------:|:----:|-------|
|+|Addition|1 + 1 = 2|
|-|Subtraction|1 - 1 = 0|
|\*|Multiplication|3 * 2 = 6|
|/|Division|4 / 2 = 2.0|
|%|Modulus|5 % 2 = 1|
|//|Floor division|5 // 2 = 2|
|\*\*|Exponentiation| 2 \*\* 3 = 8|

- Assignment operators

|Operator|Example|Is equal to|
|:--------:|:-------:|-----------|
|=|x = 12||
|+=|x += 3|x = x + 3|
|-=|x -= 3|x = x - 3|
|\*=|x \*= 3|x = x * 3|
|/=|x \/= 3|x = x / 3|
|%=|x %= 3|x = x % 3|
|//=|x //= 3|x = x // 3|
|\*\*=|x \*\*= 3|x = x \*\* 3|

- Comparison operators

|Operator|Name|Example|
|:--------:|:----:|-------|
|==|Equal|x == y|
|!=|Not equal|x != y|
|>|Greater than|x > y|
|<|Less than|x < y|
|>=|Greater than or equal to|x >= y|
|<=|Less than or equal to|x <= y|

In [ ]:
x = 1
y = 2

# note that expressions are evaluated from left to right 
# + and - have lower priority than other operators - they must be enclosed in brackets to be evaluated before other operators
print(f'1 + 2 * 2 = {1 + 2 * 2}')
print(f'(1 + 2) * 2 = {(1 + 2) * 2}')
print(f'1 / 2 * 2 = {1 / 2 * 2}')
print(f'1 / (2 * 2) = {1 / (2 * 2)}')

In [ ]:
# function eval can be used for evaluation of expressions stored as string
print('Using eval to evaluate expression:   {}'.format(eval('1 / (2 * 2)')))

## Loops and conditions

**General note:** In Python, indentation has specific purpose - it indicates block of code

### If condition

In [ ]:
print_something = True

# note that identation defined what part of the code is subordinated to the if condition
if print_something:
    print('I feel good!!!')
print('Now I don\'t feel that good.')

In [ ]:
how_do_i_feel = 'bad'

# if condition can evaluate an expression that returns boolaen value
if how_do_i_feel == 'good':
    print('I feel majestic!!!')
elif how_do_i_feel == 'bad':
    print('I feel awful!!!')
else:
    print('I don\'t now how I feel!!!')

In [ ]:
# if conditions can be submerged into another if condition. Again, indentation distinguish between given levels.
if 'I am not an emty string!':
    print('Not empty string in if condition evaluates as True. But what about empty strings?')
    if '':
        print('Empty string will also pass the condition!')
    else:
        print('Hmmm. Empty string in if condition evaluates as False.')
else:
    print('Seems like not empty string in if condition evaluates as False. Ok, what about empty strings?')
    if '':
        print('Empty string will pass the condition!')
    else:
        print('Not even empty string passed the condition.')

In [ ]:
# numbers in if condition behaves similarily to text
if 0:
    print('As for numbers - 0 will pass the condition')
elif 12:
    print('As for numbers - 0 will NOT pass the condition, any non zero number do.')
else:
    print('Seems like no numbers will pass the condition.')

In [ ]:
# And we can also use list, dictionaries and other objects in if condition
if ['Hello']:
    print('Empty list would be evaluated as False. Trust me on this.')

**General note:** Python has one special data type - None. It represents empty value or null value.

In [ ]:
variable = None
other_variable = 'not None'

if variable:
    print('How come?')
elif variable is None:
    print('We can use \'is None\' synatx to check for None value.')
    print(f'And guess what, None == None return {None == None}')

In [ ]:
# Using multipe conditions
if variable or True:
    print('We can use \'or\' and \'and\' operators as well.')

In [ ]:
# if can be written in one line, however we cannot use elif in such a case
print('one line if') if False else print('nothing happend')

### For loop
- for loop allows us to iterate over any iterable object

In [ ]:
# range is an iterable object
for i in range(5):
    print(i)

In [ ]:
# list is also iterable
for item in [1,2,3]:
    print(item)

In [ ]:
simple_dictionary = {
    'a': 0,
    'b': 1,
    'c': 2
}

# dictionary can also be used
for item in simple_dictionary:
    print(f'{item}:   {simple_dictionary[item]}')

In [ ]:
list_of_tuples = [
    ('a', 0),
    ('b', 1),
    ('c', 2)
]

# dictionary can be also used in iteration
for key, val in list_of_tuples:
    print(f'{key}:   {val}')

In [ ]:
# we can use continue and break directives
for i in range(10):
    if i % 2 == 0:
        # do next iteration
        continue
    elif i >= 8:
        # stop iteration here
        break
    else:
        print(i)

<span style="color:red">**TO DO:** Iterate from 1 to 100. Print numbers that are divisible by 9. After 80, break the iteration.</span>

#### List comprehention
- List comprehention allows to write for loop in one line
- this is very useful concept

In [ ]:
my_list = [
    1,2,3,4,5
]

# list comprehention
my_modified_list = [i + 1 for i in my_list]
print(my_modified_list)

In [ ]:
# we can use if in list comprehention
my_modified_list = [item if item % 2 == 0 else -item for item in my_list if item <= 4]
my_modified_list

**Hint:** Package tqdm allows us to display progress bar of for loops

In [ ]:
from tqdm.notebook import tqdm
import time

for i in tqdm(range(1000)):
    if i % 100 == 0 and i > 0:
        print(f'{i} / 1000')
        time.sleep(0.5)

<span style="color:red">**TO DO:** Translate string to Morse code using list comprehention.</span>

In [ ]:
string = 'SOS. Calling for help.'

morse string = 

print(morse_string)

### While loop

In [ ]:
# use while to print string encoded by morse
i = 1
while i <= len(string):
    print(morse[string[i-1].upper()], end = ' ')
    i += 1

<span style="color:red">**TO DO:** Using `while`, construct first 10 items of Fibonacci sequence (Each item is equal to the sum of previous two items; first two items are 0 and 1).</span>

In [ ]:
fibonacci_seq =

## Functions and classes

### User defined functions
- how to define function
- docstring
- function parameters
- recursive functions

In [ ]:
# simple function (wait_for_it); note that there is no returned value
def wait_for_it(time_to_wait):
    print('I started.')
    time.sleep(time_to_wait)
    print('And I am done...')
    
wait_for_it(2)

In [ ]:
# simple function with returned value
def add_four(num):
    return num + 4

add_four(-2)

<span style="color:red">**TO DO:** Define function `compute_annuity` in the cell below that will return annuity based on limit, number of payments, ir, and instalments per year.</span>
$$q = 1 + \frac{IR}{f}$$
$$A = L\frac{q^{n}(q-1)}{q^{n-1}}$$
where

- L ... limit
- A ... annuity
- n ... number of payments
- f ... payments per year
- IR ... interest rate

In [ ]:
# parameters can have default values; note that parameters without default value must preceed those with default value
def compute_annuity(limit, number_of_instalments, ir = 0.1, instalments_per_year = 12):
    """
    Computes annuity payment from other product parameters.
    
    Parameters
    ----------
    limit : number
        Credit limit.
    number_of_instalments : number
        Number of instalments.
    ir : number
        Interest rate.
    instalments_per_year: number
        Payment frequency - number of instalments per one year. Default is 12 -> monthly payments.
    """
    # place for your code
    

limit = 200000
number_of_instalments = 60
ir = 0.12
annuity = compute_annuity(
    limit = limit,
    number_of_instalments = number_of_instalments,
    ir = ir
)

print(f'Limit:                   {limit:,}'.replace(',', ' '))
print(f'Number of instalments:   {number_of_instalments}')
print(f'Interest rate:           {ir}')
print('')
print(f'Annuity:                 {annuity:,.2f}'.replace(',', ' '))

In [ ]:
?compute_annuity

In [ ]:
# using *args in parameters (join_words_to_sentence)
def join_words_to_sentence(*args):
    arg_list = []
    for arg in args:
        arg_list.append(arg)
    
    sentence = ' '.join(arg_list) + '.'
    return sentence

In [ ]:
print(join_words_to_sentence('I', 'used', 'to', 'be', 'set', 'of', 'words,', 'now', 'I', 'am', 'one', 'sentence'))

In [ ]:
my_words = [
    'I', 'used', 'to', 'be', 'set', 'of', 'words,', 'now', 'I', 'am', 'one', 'sentence'
]

# '*' in function argument has special meaning
print(join_words_to_sentence(*my_words))

In [ ]:
# recursive function
def factorial(n):
    """
    Function computes factorial recursivly.
    
    Parameters
    ----------
    n : int
        Factorial argument.
    """
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)

In [ ]:
factorial(5)

In [ ]:
# return more than one value
def min_max(list_of_values):
    return min(list_of_values), max(list_of_values)

min_val, max_val = min_max([2,5,3,6,9,8])
print(f'Minimum:   {min_val}')
print(f'Maximum:   {max_val}')

### Lambda function
- Lambda function is a shorter way of defining a function. It can also be used to define anonymous functions.

In [ ]:
# anonymous function
(lambda x: x)(1)

In [ ]:
# named lambda expression
identity = lambda x: x
identity(1)

In [ ]:
# multiple arguments in lambda expression
(lambda x, y: x + y)(3, 4)

In [ ]:
# using lambda expression for sorting a list
list_of_values = [1,2,3,4,5,6,7,8,9]
sorted(list_of_values, key = lambda x: x % 3)

### Classes in Python

***Object Oriented Programming***

Object Oriented Programming is a programming paradigm - it presents different way of thinking about construction of programms. Basic building blocks are objects. Object is an construct that holds data (in form of attributes or properties) and logic that can be applied to this data (methods).

Objects, their structure and functionality, are defined in classes. We say object is an instance of class. It is like having a recipe for a cake (this would represent a class) and then the cake created based on this recipe (this would be object, an instance of a class). We can have multiple cakes cooked by one recipe same as we can have multiple objects of one class.

Objects brings following features:

- Encapsulation - object holds the data and the logic that can be applied on them. Also we can hide some functionality from the end user.
- Composition - object can contain other object. For instance, object Employment can contain object Address.
- Inheritance - we can arrange object hierarchy - child class is an extention of parent class, it knows everything parent does and also something that parent does not know.
- Overloading methods - the same method can apply different logic for different classes. For instance operator '+' has different functionality when applied on strings or integers

Syntax of class definition:

- "functions" defined inside a class are called **methods** and their functionality is available only inside given class and its descendants
- Each class must have `__init__()` method - this is called **constructor** and it is executed every time a new instance of the class is being established
- First parameter of \_\_init\_\_ method is always `self` - this represents the object's storage place. In `self` we store data that should be available inside the object. Data are stored as **attributes**.

<span style="color:red">Define class Roulette. In this roulette only odd/even and single digit bets are accepted. Win for odd/even is 2*bet. Win for single digit is 35*bet.</span>

**Roulette**
- attributes: 
    - remaining_money - initial remaining_money is set in constructor, then remianing_money changes as the gamer win or loose
    - bet_history - a list of gains (negative if lost, positive if win). Each bet adds one more item to bet_history.
- methods:
    - bet_even_odd - roulette is rolled and remaining money is modified based on result (win/loss)
    - bet_single_number - roulette is rolled and remaining money is modified based on result (win/loss)
    - available_bet - at the beginning of a bet (even/odd, single number) this function checks if gambles has enough resources. In case of remaining money being zero, bet is not accepted, in case of remaining money being less than bet, only bet amount is replaced with remianing money
    
**Hints:**

- Each class must have constructor method
- to generate roulette output, use random.randint(0,36) - this will generate integer number between 0 and 36

In [ ]:
class Roulette:
    def __init__(self, total_money):
        self.remaining_money = total_money
        self.bet_history = []
    
    def roll_roulette(self):
        return random.randint(0,36)
    
    def available_bet(self, bet_amount):
        if self.remaining_money == 0:
            print('You have lost everything. Get lost!')
            return 0
        else:
            return min(self.remaining_money, bet_amount)
    
    def bet_even_odd(self, bet, bet_amount):
        bet_amount = self.available_bet(bet_amount)
        
        num = self.roll_roulette()
        if num == 0:
            num_type = 'zero'
        elif num % 2 == 0:
            num_type = 'odd'
        else:
            num_type = 'even'
        
        if num_type == bet:
            gain = 2 * bet_amount - bet_amount
        else:
            gain = -bet_amount
            
        self.remaining_money += gain
        self.bet_history.append(gain)
        
    def bet_single_number(self, bet, bet_amount):
        bet_amount = self.available_bet(bet_amount)
        
        num = self.roll_roulette()
        if bet == num:
            gain = 35 * bet_amount - bet_amount
        else:
            gain = -bet_amount
            
        self.remaining_money += gain
        self.bet_history.append(gain)

In [ ]:
import random
# generate integer between 0 and 36
random.randint(0,36)

In [ ]:
def gamble_roulette(init_money, strategy, bet_amount = 10):
    gambler = Roulette(init_money)

    bet_amount = bet_amount
    while gambler.remaining_money > 0:
        if strategy == 'odd_even':
            my_bet = 'odd' if random.random() < 0.5 else 'even'
            gambler.bet_even_odd(my_bet, bet_amount)
        elif strategy == 'single_digit':
            my_bet = random.randint(0,36)
            gambler.bet_single_number(my_bet, bet_amount)
    
    return gambler.bet_history

In [ ]:
import matplotlib.pyplot as plt
import numpy as np


h_oe = gamble_roulette(1000, 'odd_even')
h_sd = gamble_roulette(1000, 'single_digit')

plt.plot(np.cumsum(h_oe), label = 'odd/even')
plt.plot(np.cumsum(h_sd), label = 'single digit')
plt.xlabel('bet order')
plt.ylabel('total gain')
plt.legend(loc = 'best')
plt.show()

In [ ]:
from tqdm.notebook import tqdm

In [ ]:
n_runs = 100

odd_even = []
single_digit = []
for i in tqdm(range(n_runs)):
    h_oe = gamble_roulette(1000, 'odd_even')
    h_sd = gamble_roulette(1000, 'single_digit')
    
    odd_even.append(len(h_oe))
    single_digit.append(len(h_sd))

In [ ]:
plt.boxplot([odd_even, single_digit], labels = ['odd/even', 'single_digit'])
plt.ylim([0,10000])
plt.show()

## Exception handling
- When a program hits an error, an *exception* is being raised.
- Python defines various types of exceptions - see <a href="https://docs.python.org/3/library/exceptions.html" target="_blank">python exceptions</a> for list of build-in exceptions.
- Few examples of exceptions:

|Exception|Reason|Example|
|:-|:-|:-|
|TypeError|Operation or function is applied on an object of inappropriate type|Division of two strings|
|ValueError|Operation or function receives an argument that has the right type but an inappropriate value|Square root of negative number|
|KeyError|Dictionary key is not found in the set of existing keys|Accessing non-existing dictionary key|
|ZeroDivisionError|Second argument of a division or modulo operation is zero|Division by zero|
|ModuleNotFoundError|Module could not be located|Trying to import non existing module|

- Exceptions can be handled - if an exception is encountered, we might want the code not to break, but rather do something else. Or we can modify displayed error message to be more informative.
- Exeption handling is done using `try` and `except` statements

In [ ]:
# 'aaa' / 'bbb'

# import math
# math.sqrt(-5)

# dictionary = {
#     1: 1,
#     2: 2
# }
# dictionary[3]

# 1 / 0

# import xgboost2

### Handling an exceptions

In [ ]:
numerator = 1
denominator = 0

fraction = numerator / denominator

In [ ]:
# basic handling of ZeroDivisionError
try:
    fraction = numerator / denominator
except:
    fraction = 0
    
print(fraction)

In [ ]:
# Handling specific type of an error separately
denominator = 'aaa'

try:
    fraction = numerator / denominator
except ZeroDivisionError:
    fraction = 0
    
print(fraction)

- Finally is an *cleanup* handler. It is being executed after try and except clauses.

In [ ]:
denominator = 0

try:
    fraction = numerator / denominator
except ZeroDivisionError:
    print(-1)
    fraction = 0
except ValueError:
    fraction = None
finally:
    print('Running finally handler...')
    
print(fraction)

### Raising an exception
- exceptions can be raised manually

In [ ]:
# Enforcing variable pi to be set with correct value
pi = 2.7183

if round(pi, 4) != 3.1415:
    raise ValueError

In [ ]:
# Adding user defined error message
pi = 2.7183

if round(pi, 4) != 3.1415:
    raise ValueError('Any child knows that pi is equal to 3.1415!')

<span style="color:red">**TO DO:** Modify compute annuity function in the following fashion:</span>

- if any of product parameters passed to the function has a form of not numerical string, raise TypeError
- if any of product parameters is negative, raise ValueError
- note: limit = '10000' is a correct input

In [ ]:
# add check for correct values to compute_annuity function - TypeError if parameters are not numerical (try retyping), 
# ValueError if negative values
def compute_annuity(limit, number_of_instalments, ir = 0.1, instalments_per_year = 12):
    """
    Computes annuity payment from other product parameters.
    
    Parameters
    ----------
    limit : number
        Credit limit.
    number_of_instalments : number
        Number of instalments.
    ir : number
        Interest rate.
    instalments_per_year: number
        Payment frequency - number of instalments per one year. Default is 12 -> monthly payments.
    """
    q = 1 + ir / instalments_per_year
    annuity = limit * q ** number_of_instalments * (q - 1) / (q ** number_of_instalments - 1)
    return annuity

limit = 200000
number_of_instalments = 60
ir = 0.12
annuity = compute_annuity(
    limit = limit,
    number_of_instalments = number_of_instalments,
    ir = ir
)

print(f'Limit:                   {limit:,}'.replace(',', ' '))
print(f'Number of instalments:   {number_of_instalments}')
print(f'Interest rate:           {ir}')
print('')
print(f'Annuity:                 {annuity:,.2f}'.replace(',', ' '))

In [ ]:
compute_annuity(
    limit=100000,
    number_of_instalments=24
)

## Importing packages
- how to install packages
- different ways to import packages
- user defined packages

**General note:** using `!` at the beggining of the line, means that the command is executed in command line

### Installation of python packages
`pip` is a program for managment of python packages. By calling `pip install package_name` in command line, desired package will be automatically dowloaded and installed to proper location.

Using `pip` we can also uninstall packages or specify a version of package to be installed.

In [ ]:
# !pip install xgboost (do not run)

In [ ]:
# !pip uninstall xgboost (do not run)

In [ ]:
# !pip install xgboost=0.90 (do not run)

### Importing packages

In [ ]:
# basic way to import package
import numpy

# We can use functionality defined in numpy package now
numpy.mean([1,2,3,4])

In [ ]:
# removing numpy from packages I have access to
del numpy

# now I cannot use numpy functionality
numpy.mean([1,2,3,4])

In [ ]:
# importing package and defining alias
import numpy as np

# numpy functionality is now available under np
vector = [1,2,3,4] 
print(f'Vector mean: {np.mean(vector)}')
print(f'Vector standard deviation: {np.std(vector)}')

In [ ]:
del np

In [ ]:
# importing only part of the package
from numpy import mean

vector = [1,2,3,4] 
print(f'Vector mean: {mean(vector)}')
print(f'Vector standard deviation: {std(vector)}')

In [ ]:
# importing all functionality from package
from numpy import *

vector = [1,2,3,4] 
print(f'Vector mean: {mean(vector)}')
print(f'Vector standard deviation: {std(vector)}')

### User defined packages
First create a folder named *user_library* at the location of current script. Inside create a *roulette.py* file a copy paste there codes for definition of class Roulette.

In [ ]:
import user_library.roulette as rl

In [ ]:
roulette = rl.Roulette(1000)

In [ ]:
roulette.bet_even_odd('even', 100)

In [ ]:
roulette.bet_history

**General note:** Sometimes in python scripts you might encounter a condition `if __name__ == '__main__':`.

At the very beginning of python code execution, several special variables (such as `__name__`) are assigned. The entering point of the application (the main program, the file that we sent to python interpreter) has assgined a value `__main__` in variable `__name__`. The main program usually uses other imported modules. Those modules has also variable `__name__` assigned. The value of this variable will be equal to the location of the module.

*Example:*
- *We run `python main_script.py`. The code written in main_script.py has assigned value of `__name__` equal to `__main__`.*
- Inside `main_script.py` we import package `support_functions` that is defined in file `support_functions.py`. Any code written in `support_functions` has `__name__ = 'support_functions'`.

# Loading data
- os and sys packages
- retrieving input from console
- using relative and absoluth paths
- loading data from txt / csv / pickle
- saving data

## sys package
- sys ... System-specific parameters and functions

In [ ]:
import sys

In [ ]:
# system paths (defines location where python searches for packages)
sys.path

In [ ]:
my_integer = 1

# size of object in bytes (getsizeof)
sys.getsizeof(my_integer)

In [ ]:
# list available packages (modules)
list(sys.modules.keys())

## os package
- os ... Miscellaneous operating system interfaces

In [ ]:
import os

In [ ]:
# current working directory
os.getcwd()

In [ ]:
# list content of given folder
os.listdir(os.getcwd())

In [ ]:
# create folder...
os.mkdir('test_folder')

In [ ]:
# ...and remove it
os.removedirs('test_folder')

In [ ]:
os.path.exists('C:\\Users\\tyblondr\\data-science-2\\Practicals\\02_python_intro')

In [ ]:
os.path.isfile('C:\\Users\\tyblondr\\data-science-2\\Practicals\\02_python_intro\\python_intro.ipynb')

## Input from console

In [ ]:
my_input = input('Give me some input please:   ')

print(f'Your input was doubled:      {2*my_input}')

<span style="color:red">**TO DO:** Write 'child calculator'. It will generate two integers so that their sum is not greater than 100. It will ask user to enter their sum and it will check answer correctness.</span>

**Hint:** 
- str.isnumeric() checks if string contains only digits
- use random.randint to generate random integer (package random)

In [ ]:
import random

In [ ]:
child_calculator()

## Relative and absolut paths

### Relative path

In [ ]:
# using relative path = current working directory + filename
os.path.isfile('python_intro.ipynb')

In [ ]:
# we can go deeper from CWD
os.path.isfile('user_library/roulette.py')

In [ ]:
# .. means go on level back in folder structure
os.path.isfile('user_library/../python_intro.ipynb')

### Absoluth path

In [ ]:
# check isfile with absolute path
os.path.isfile('C:\\Users\\tyblondr\\data-science-2\\Practicals\\02_python_intro\\python_intro.ipynb')

In [ ]:
# this used to be true, now better in new versions, one can use any slashes

print('This is a valid path:       C:\\Users\\tyblondr')
print(r'This is a valid path:       C:\Users\tyblondr')
print('This is a valid path:   C:\\Users\\tyblondr')
print(r'This is a valid path:   C:/Users/tyblondr')

## Load and save data

### Text files

In [ ]:
file_content = """Hello!
What should I do? I don't know.
Well, good bye.
"""

In [ ]:
# write text file
with open('test.txt', 'a') as file:
    file.write(file_content)

In [ ]:
# read text file
with open('test.txt', 'r') as file:
    data = file.read()
    
print(data)

In [ ]:
import time

# read file by lines
with open('test.txt', 'r') as file:
    line = True
    while line:
        line = file.readline()
        print(line)
        time.sleep(0.5)

### pickle files
- pickle are binary files.

In [ ]:
import pickle

In [ ]:
matrix = [
    [1, 2],
    [3, 4]
]

# create pickle file...
with open('test_pickle.pickle', 'wb') as file:
    pickle.dump(matrix, file)

In [ ]:
# ...and load it again
with open('test_pickle.pickle', 'rb') as file:
    data = pickle.load(file)
    
data

### json files

In [ ]:
import json

my_books = {
    'scifi': {
        'Asimov': 'Nadace',
        'Orwell': '1984'
    },
    'fantasy': {
        'Sapkowski': 'Witcher',
        'Tolkien': 'Lord of the rings'
    }
}

# save json to the disk; use indent, sort_key a ensure_ascii
with open('my_library.json', 'w') as file:
    json.dump(my_books, file, indent=4, sort_keys=True, ensure_ascii=False)

In [ ]:
# load json
with open('my_library.json', 'r') as file:
    mb = json.load(file)

### csv files

In [ ]:
import pandas as pd

In [ ]:
data = [
    [1, 2],
    [3, 4]
]

data = pd.DataFrame(data, columns = ['col1', 'col2'])
data

In [ ]:
data.to_csv('test_csv.csv', sep = ';', index = False)

In [ ]:
loaded_data = pd.read_csv('test_csv.csv', sep = ';', header = 0, nrows = 1, encoding = 'utf-8')
loaded_data

# Pandas and numpy
- pandas = python data analysis library
- numpy = numerical python

## DataFrame

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = [
    (1, 2),
    (3, 4)
]

df = pd.DataFrame(df, columns = ['col1', 'col2'])
df

   col1  col2
0     1     2
1     3     4

In [5]:
df = {
    'a': [1,2,3,4],
    'b': [5,6,7,8],
}

df = pd.DataFrame(df)
df

   a  b
0  1  5
1  2  6
2  3  7
3  4  8

In [8]:
from pathlib import Path
data_file = Path("/Users/goumont/Desktop/Data/data_devsample.csv")

In [9]:
data = pd.read_csv(data_file, sep = ',', encoding = 'utf-8', low_memory=False)
print(f'data is object of type:   {type(data)}')
print(f'Number of rows:           {data.shape[0]}')
print(f'Number of columns:        {data.shape[1]}')

data is object of type:   <class 'pandas.core.frame.DataFrame'>
Number of rows:           80000
Number of columns:        197

**Note:** pd.DataFrame is similar to SQL table - columns have their names and data types, table has index

In [10]:
data.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,MEAN_AMTCR_OVERDUE_0M_INFM_TYPE_EQ_ACTIVE_DIV_MEAN_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MEAN_AMTCR_OVERDUE_0M_12M_TYPE_EQ_ACTIVE_DIV_MEAN_AMTCR_0M_12M_TYPE_EQ_ACTIVE,MEAN_AMTCR_OVERDUE_0M_INFM_TYPE_EQ_CLOSED_DIV_MEAN_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MEAN_AMTCR_OVERDUE_0M_12M_TYPE_EQ_CLOSED_DIV_MEAN_AMTCR_0M_12M_TYPE_EQ_CLOSED,FIRST_TRANSACTION_TIME_MONTHS,LAST_TRANSACTION_TIME_MONTHS,TIME,BASE,DAY,MONTH
0,215138,0.0,Cash loans,M,N,Y,0.0,135000.0,646920.0,25195.5,...,0.0,NaN,0.0,NaN,37.0,28.0,2018-06-23,1,20180623,201806
1,325963,0.0,Cash loans,M,Y,Y,0.0,135000.0,740218.5,40284.0,...,0.0,0.0,0.0,NaN,3.0,18.0,2018-06-16,1,20180616,201806
2,206923,0.0,Cash loans,F,N,Y,0.0,180000.0,339241.5,12919.5,...,0.0,NaN,0.0,NaN,73.0,61.0,2018-06-19,1,20180619,201806
3,265855,0.0,Cash loans,F,N,Y,0.0,180000.0,1264428.0,37098.0,...,0.0,0.0,NaN,NaN,36.0,4.0,2018-08-09,1,20180809,201808
4,359795,0.0,Revolving loans,F,N,Y,NaN,76500.0,202500.0,10125.0,...,NaN,NaN,0.0,0.0,12.0,12.0,2018-11-13,1,20181113,201811

In [11]:
# this controls how many columns are displayed
pd.options.display.max_columns = 200

data.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,MIN_AMTCR_0M_INFM,MAX_AMTCR_0M_INFM,MEAN_AMTCR_0M_INFM,MEDIAN_AMTCR_0M_INFM,STD_AMTCR_0M_INFM,MIN_AMTCR_0M_6M,MAX_AMTCR_0M_6M,MEAN_AMTCR_0M_6M,MEDIAN_AMTCR_0M_6M,STD_AMTCR_0M_6M,MIN_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MAX_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MEAN_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MEDIAN_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,STD_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MIN_AMTCR_0M_6M_TYPE_EQ_ACTIVE,MAX_AMTCR_0M_6M_TYPE_EQ_ACTIVE,MEAN_AMTCR_0M_6M_TYPE_EQ_ACTIVE,MEDIAN_AMTCR_0M_6M_TYPE_EQ_ACTIVE,STD_AMTCR_0M_6M_TYPE_EQ_ACTIVE,MIN_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MAX_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MEAN_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MEDIAN_AMTCR_0M_INFM_TYPE_EQ_CLOSED,STD_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MIN_AMTCR_0M_6M_TYPE_EQ_CLOSED,MAX_AMTCR_0M_6M_TYPE_EQ_CLOSED,MEAN_AMTCR_0M_6M_TYPE_EQ_CLOSED,MEDIAN_AMTCR_0M_6M_TYPE_EQ_CLOSED,STD_AMTCR_0M_6M_TYPE_EQ_CLOSED,MIN_DPD_0M_INFM,MAX_DPD_0M_INFM,MEAN_DPD_0M_INFM,MEDIAN_DPD_0M_INFM,STD_DPD_0M_INFM,MIN_DPD_0M_6M,MAX_DPD_0M_6M,MEAN_DPD_0M_6M,MEDIAN_DPD_0M_6M,STD_DPD_0M_6M,MIN_DPD_0M_INFM_TYPE_EQ_ACTIVE,MAX_DPD_0M_INFM_TYPE_EQ_ACTIVE,MEAN_DPD_0M_INFM_TYPE_EQ_ACTIVE,MEDIAN_DPD_0M_INFM_TYPE_EQ_ACTIVE,STD_DPD_0M_INFM_TYPE_EQ_ACTIVE,MIN_DPD_0M_6M_TYPE_EQ_ACTIVE,MAX_DPD_0M_6M_TYPE_EQ_ACTIVE,MEAN_DPD_0M_6M_TYPE_EQ_ACTIVE,MEDIAN_DPD_0M_6M_TYPE_EQ_ACTIVE,STD_DPD_0M_6M_TYPE_EQ_ACTIVE,MIN_DPD_0M_INFM_TYPE_EQ_CLOSED,MAX_DPD_0M_INFM_TYPE_EQ_CLOSED,MEAN_DPD_0M_INFM_TYPE_EQ_CLOSED,MEDIAN_DPD_0M_INFM_TYPE_EQ_CLOSED,STD_DPD_0M_INFM_TYPE_EQ_CLOSED,MIN_DPD_0M_6M_TYPE_EQ_CLOSED,MAX_DPD_0M_6M_TYPE_EQ_CLOSED,MEAN_DPD_0M_6M_TYPE_EQ_CLOSED,MEDIAN_DPD_0M_6M_TYPE_EQ_CLOSED,STD_DPD_0M_6M_TYPE_EQ_CLOSED,MEAN_AMTCR_1M_3M_DIV_MEAN_AMTCR_3M_12M,MEAN_AMTCR_1M_3M_TYPE_EQ_ACTIVE_DIV_MEAN_AMTCR_3M_12M_TYPE_EQ_ACTIVE,MEAN_AMTCR_1M_3M_TYPE_EQ_CLOSED_DIV_MEAN_AMTCR_3M_12M_TYPE_EQ_CLOSED,MEAN_AMTCR_OVERDUE_0M_INFM_DIV_MEAN_AMTCR_0M_INFM,MEAN_AMTCR_OVERDUE_0M_12M_DIV_MEAN_AMTCR_0M_12M,MEAN_AMTCR_OVERDUE_0M_INFM_TYPE_EQ_ACTIVE_DIV_MEAN_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MEAN_AMTCR_OVERDUE_0M_12M_TYPE_EQ_ACTIVE_DIV_MEAN_AMTCR_0M_12M_TYPE_EQ_ACTIVE,MEAN_AMTCR_OVERDUE_0M_INFM_TYPE_EQ_CLOSED_DIV_MEAN_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MEAN_AMTCR_OVERDUE_0M_12M_TYPE_EQ_CLOSED_DIV_MEAN_AMTCR_0M_12M_TYPE_EQ_CLOSED,FIRST_TRANSACTION_TIME_MONTHS,LAST_TRANSACTION_TIME_MONTHS,TIME,BASE,DAY,MONTH
0,215138,0.0,Cash loans,M,N,Y,0.0,135000.0,646920.0,25195.5,540000.0,Family,Working,Secondary / secondary special,Married,House / apartment,0.031329,-15665.0,-1503,-3818.0,-4071,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,SATURDAY,14,0,0,0,0,0,0,Transport: type 2,0.520144,0.500603,0.558507,0.0649,0.0546,0.9911,NaN,NaN,0.08,0.0690,0.3750,NaN,0.0193,NaN,0.0851,NaN,0.0145,0.0662,0.0567,0.9911,NaN,NaN,0.0806,0.0690,0.3750,NaN,0.0197,NaN,0.0887,NaN,0.0153,0.0656,0.0546,0.9911,NaN,NaN,0.08,0.0690,0.3750,NaN,0.0196,NaN,0.0866,NaN,0.0148,NaN,block of flats,0.0704,Panel,No,2.0,1.0,2.0,1.0,-1120.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,4.5,1345500.0,451410.75,270000.0,483254.347177,NaN,NaN,NaN,NaN,NaN,4.5,630000.0,315002.25,315002.25,445474.090167,NaN,NaN,NaN,NaN,NaN,192960.0,1345500.0,519615.0,270000.0,551786.437764,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,37.0,28.0,2018-06-23,1,20180623,201806
1,325963,0.0,Cash loans,M,Y,Y,0.0,135000.0,740218.5,40284.0,639000.0,Unaccompanied,Pensioner,Secondary / secondary special,Married,With parents,0.018850,-16874.0,365243,-594.0,-406,8.0,1,0,0,1,0,0,NaN,2.0,2,2,THURSDAY,15,0,0,0,0,0,0,XNA,NaN,0.352930,0.411849,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,-197.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0,19777.5,84586.5,52182.00,52182.0,45826.883382,19777.5,19777.5,19777.5,19777.5,NaN,19777.5,19777.5,19777.50,19777.50,NaN,19777.5,19777.5,19777.5,19777.5,NaN,84586.5,84586.5,84586.5,84586.5,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,3.0,18.0,2018-06-16,1,20180616,201806
2,206923,0.0,Cash loans,F,N,Y,0.0,180000.0,339241.5,12919.5,238500.0,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,0.010032,-20011.0,-10792,-8359.0,-3310,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,WEDNESDAY,5,0,0,0,0,0,0,Business Entity Type 2,0.784819,0.511956,0.266457,0.0371,0.0482,0.9881,0.8368,0.0074,0.00,0.0690,0.2083,0.25,0.0831,0.0303,0.0465,0.0,0.0000,0.0378,0.0500,0.9881,0.8432,0.0075,0.0000,0.0690,0.2083,0.25,0.0850,0.0331,0.0484,0.0,0.0000,0.0375,0.0482,0.9881,0.8390,0.0075,0.00,0.0690,0.2083,0.25,0.0846,0.0308,0.0473,0.0,0.0000,reg oper account,block of flats,0.0406,Panel,No,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,92299.5,168952.5,130900.50,131175.0,32276.688469,NaN,NaN,NaN,NaN,NaN,121500.0,121500.0,121500.00,121500.00,NaN,NaN,NaN,NaN,NaN,NaN,92299.5,168952.5,134034.0,140850.0,38778.395973,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,0.0,NaN,73.0,61.0,2018-06-19,1,20180619,201806
3,265855,0.0,Cash loans,F,N,Y,0.0,180000.0,1264428.0,37098.0,990000.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married,House / apartment,0.035792,-10954.0,-2513,-4431.0,-2617,NaN,1,1,0,1,0,0,Laborers,2.0,2,2,TUESDAY,14,0,0,0,1,1,1,Business Entity Type 3,0.559675,0.627377,0.418854,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,0.0,5.0,0.0,-1457.0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0,91287.0,405000.0,264789.00,298080.0,159484.104547,91287.0,91287.0,91287.0,91287.0,NaN,91287.0,405000.0,264789.00,298080.00,159484.104547,91287.0,91287.0,91287.0,91287.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,36.0,4.0,2018-08-09,1,20180809,201808
4,359795,0.0,Revolving loans,F,N,Y,NaN,76500.0,202500.0,10125.0,202500.0,Unaccompanied,Working,Higher education,Married,House / apartment,0.018209,NaN,-2855,-3110.0,-4059,NaN,1,1,0,1,1,0,NaN,3.0,3,3,WEDNESDAY,11,0,0,0,0,0,0,Housing,NaN,0.535542,0.332851,0.1856,0.1437,0.9861,0.8028,0.0105,0.20,0.1724,0.3333,NaN,0.0966,0.1513,0.1209,0.0,0.2857,0.1891,0.1491,0.9861,0.8105,0.0106,0.2014,0.1724,0.3333,NaN,0.0988,0.1653,0.1260,0.0,0.3024,0.1874,0.1437,0.9861,0.8054,0.0106,0.20,0.1724,0.3333,NaN,0.0983,0.1539,0.1231,0.0,0.2916,org spec account,block of flats,0.1572,Panel,No,0.0,0.0,0.0,0.0,-1920.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,35460.0,35460.0,35460.00,35460.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35460.0,35460.0,35460.0,35460.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,0.0,0.0,12.0,12.0,2018-11-13,1,20181113,201811

In [12]:
# get descriptive stats

import warnings
warnings.simplefilter(action = "ignore", category = RuntimeWarning) # to get rid of RuntimeWarning: invalid value encountered in subtract

data.describe()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,MIN_AMTCR_0M_INFM,MAX_AMTCR_0M_INFM,MEAN_AMTCR_0M_INFM,MEDIAN_AMTCR_0M_INFM,STD_AMTCR_0M_INFM,MIN_AMTCR_0M_6M,MAX_AMTCR_0M_6M,MEAN_AMTCR_0M_6M,MEDIAN_AMTCR_0M_6M,STD_AMTCR_0M_6M,MIN_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MAX_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MEAN_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MEDIAN_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,STD_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MIN_AMTCR_0M_6M_TYPE_EQ_ACTIVE,MAX_AMTCR_0M_6M_TYPE_EQ_ACTIVE,MEAN_AMTCR_0M_6M_TYPE_EQ_ACTIVE,MEDIAN_AMTCR_0M_6M_TYPE_EQ_ACTIVE,STD_AMTCR_0M_6M_TYPE_EQ_ACTIVE,MIN_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MAX_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MEAN_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MEDIAN_AMTCR_0M_INFM_TYPE_EQ_CLOSED,STD_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MIN_AMTCR_0M_6M_TYPE_EQ_CLOSED,MAX_AMTCR_0M_6M_TYPE_EQ_CLOSED,MEAN_AMTCR_0M_6M_TYPE_EQ_CLOSED,MEDIAN_AMTCR_0M_6M_TYPE_EQ_CLOSED,STD_AMTCR_0M_6M_TYPE_EQ_CLOSED,MIN_DPD_0M_INFM,MAX_DPD_0M_INFM,MEAN_DPD_0M_INFM,MEDIAN_DPD_0M_INFM,STD_DPD_0M_INFM,MIN_DPD_0M_6M,MAX_DPD_0M_6M,MEAN_DPD_0M_6M,MEDIAN_DPD_0M_6M,STD_DPD_0M_6M,MIN_DPD_0M_INFM_TYPE_EQ_ACTIVE,MAX_DPD_0M_INFM_TYPE_EQ_ACTIVE,MEAN_DPD_0M_INFM_TYPE_EQ_ACTIVE,MEDIAN_DPD_0M_INFM_TYPE_EQ_ACTIVE,STD_DPD_0M_INFM_TYPE_EQ_ACTIVE,MIN_DPD_0M_6M_TYPE_EQ_ACTIVE,MAX_DPD_0M_6M_TYPE_EQ_ACTIVE,MEAN_DPD_0M_6M_TYPE_EQ_ACTIVE,MEDIAN_DPD_0M_6M_TYPE_EQ_ACTIVE,STD_DPD_0M_6M_TYPE_EQ_ACTIVE,MIN_DPD_0M_INFM_TYPE_EQ_CLOSED,MAX_DPD_0M_INFM_TYPE_EQ_CLOSED,MEAN_DPD_0M_INFM_TYPE_EQ_CLOSED,MEDIAN_DPD_0M_INFM_TYPE_EQ_CLOSED,STD_DPD_0M_INFM_TYPE_EQ_CLOSED,MIN_DPD_0M_6M_TYPE_EQ_CLOSED,MAX_DPD_0M_6M_TYPE_EQ_CLOSED,MEAN_DPD_0M_6M_TYPE_EQ_CLOSED,MEDIAN_DPD_0M_6M_TYPE_EQ_CLOSED,STD_DPD_0M_6M_TYPE_EQ_CLOSED,MEAN_AMTCR_1M_3M_DIV_MEAN_AMTCR_3M_12M,MEAN_AMTCR_1M_3M_TYPE_EQ_ACTIVE_DIV_MEAN_AMTCR_3M_12M_TYPE_EQ_ACTIVE,MEAN_AMTCR_1M_3M_TYPE_EQ_CLOSED_DIV_MEAN_AMTCR_3M_12M_TYPE_EQ_CLOSED,MEAN_AMTCR_OVERDUE_0M_INFM_DIV_MEAN_AMTCR_0M_INFM,MEAN_AMTCR_OVERDUE_0M_12M_DIV_MEAN_AMTCR_0M_12M,MEAN_AMTCR_OVERDUE_0M_INFM_TYPE_EQ_ACTIVE_DIV_MEAN_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MEAN_AMTCR_OVERDUE_0M_12M_TYPE_EQ_ACTIVE_DIV_MEAN_AMTCR_0M_12M_TYPE_EQ_ACTIVE,MEAN_AMTCR_OVERDUE_0M_INFM_TYPE_EQ_CLOSED_DIV_MEAN_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MEAN_AMTCR_OVERDUE_0M_12M_TYPE_EQ_CLOSED_DIV_MEAN_AMTCR_0M_12M_TYPE_EQ_CLOSED,FIRST_TRANSACTION_TIME_MONTHS,LAST_TRANSACTION_TIME_MONTHS,BASE,DAY,MONTH
count,80000.000000,80000.000000,55035.000000,8.000000e+04,8.000000e+04,79994.000000,7.993700e+04,80000.000000,59780.00000,80000.000000,80000.000000,80000.000000,27316.000000,80000.0,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,34846.000000,79830.000000,64067.000000,39464.000000,33183.000000,40971.000000,26643.000000,23938.000000,37415.000000,39744.000000,40221.000000,25594.000000,32469.000000,25225.000000,39861.000000,24335.000000,35892.000000,39464.000000,33183.000000,40971.000000,26643.000000,23938.000000,37415.000000,39744.000000,40221.000000,25594.000000,32469.000000,25225.000000,39861.000000,24335.000000,35892.000000,39464.000000,33183.000000,40971.000000,26643.000000,23938.000000,37415.000000,39744.000000,40221.000000,25594.000000,32469.000000,25225.000000,39861.000000,24335.000000,35892.000000,41413.000000,79733.000000,79733.000000,79733.000000,79733.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.0,80000.000000,80000.0,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,69202.000000,69202.000000,69202.000000,69202.000000,69202.000000,69202.000000,4.964700e+04,4.964700e+04,4.964700e+04,4.964700e+04,2.863600e+04,8.332000e+03,8.332000e+03,8.332000e+03,8.332000e+03,9.920000e+02,2.946000e+04,2.946000e+04,2.946000e+04,2.946000e+04,8.692000e+03,7.502000e+03,7.502000e+03,7.502000e+03,7.502000e+03,6.290000e+02,3.774700e+04,3.774700e+04,3.774700e+04,3.774700e+04,1.754500e+04,1.123000e+03,1.123000e+03,1.123000e+03,1.123000e+03,2.000000e+02,49647.000000,49647.000000,49647.000000,49647.000000,28636.000000,8332.000000,8332.000000,8332.000000,8332.000000,992.000000,29460.000000,29460.000000,29460.000000,29460.000000,8692.000000,7502.000000,7502.000000,7502.000000,7502.000000,629.000000,37747.000000,37747.000000,37747.000000,37747.000000,17545.000000,1123.0,1123.0,1123.0,1123.0,200.0,826.000000,480.000000,136.000000,48910.0,16914.0,28407.0,14243.0,3.715600e+04,3833.0,49647.000000,49647.000000,80000.0,8.000000e+04,80000.000000
mean,278160.918850,0.080200,0.324648,1.682663e+05,5.982419e+05,27115.320924,5.376062e+05,0.020899,-16031.07740,63636.234238,-4978.924851,-3001.864075,12.091119,1.0,0.820400,0.198625,0.998250,0.283100,0.055875,2.154425,2.050687,2.031062,12.072000,0.015200,0.050700,0.040750,0.079175,0.231988,0.180638,0.501278,0.514797,0.511271,0.117545,0.088836,0.977852,0.752290,0.044937,0.079072,0.150143,0.225410,0.232124,0.065884,0.101017,0.107678,0.008634,0.028316,0.114319,0.087858,0.977251,0.759385,0.042826,0.074590,0.145539,0.221589,0.228336,0.064436,0.105748,0.106196,0.007910,0.027049,0.117961,0.088312,0.977882,0.755542,0.044898,0.078174,0.149642,0.225014,0.231878,0.066722,0.102156,0.108885,0.008481,0.028289,0.102511,1.414621,0.143002,1.397928,0.098692,-964.726887,0.000050,0.709075,0.000150,0.014762,0.088637,0.000150,0.081750,0.004000,0.0,0.004025,0.0,0.003687,0.003325,0.001375,0.009675,0.000188,0.008375,0.000487,0.000500,0.000400,0.006662,0.007456,0.033019,0.265961,0.265050,1.898876,2.174489e+05,5.730609e+05,3.612088e+05,3.244880e+05,3.403966e+05,3.630318e+05,4.004173e+05,3.812033e+05,3.803529e+05,2.148186e+05,4.521546e+05,6.526904e+05,5.462184e+05,5.364440e+05,4.413954e+05,3.956119e+05,4.263778e+05,4.108470e+05,4.105890e+05,2.551735e+05,1.756302e+05,3.453890e+05,2.484649e+05,2.342851e+05,2.112701e+05,1.332824e+05,1.399345e+05,1.365120e+05,1.364546e+05,2.463133e+04,0.424980,1.440349,0.818269,0.650946,1.082080,0.100816,0.103817,0.102316,0.102316,0.017820,1.332043,2.163103,1.695063,1.599321,1.849370,0.113836,0.115303,0.114569,0.114569,0.012366,0.120063,0.206215,0.163139,0.163139,0.131064,0.0,0.0,0.0,0.0,0.0,inf,inf,inf,inf,inf,inf,inf,6.318908e-07,0.0,36.875904,36.835841,1.0,2.018067e+07,201806.523287
std,102712.983646,0.271604,0.637932,1.092775e+05,4.002051e+05,14471.545555,3.674006e+05,0.013846,4365.52899,141122.463859,3514.337620,1506.200651,11.990588,0.0,0.383856,0.398968,0.041797,0.450507,0.229682,0.910007,0.509383,0.503191,3.274492,0.122348,0.219386,0.197712,0.270013,0.422104,0.384720,0.210864,0.191141,0.194762,0.107710,0.083747,0.058457,0.111862,0.076364,0.134956,0.100020,0.144488,0.161035,0.079140,0.092739,0.110752,0.047427,0.069154,0.107680,0.085682,0.063114,0.108773,0.074788,0.132909,0.100995,0.143752,0.160770,0.079852,0.097733,0.112075,0.045836,0.070336,0.108671,0.083402,0.059210,0.110681,0.076563,0.134902,0.100352,0.144937,0.161593,0.080229,0.093791,0.112493,0.047284,0.070028,0.107099,2.327886,0.442464,2.307764,0.355815,828.199522,0.007071,0.454192,0.012247,0.120602,0.284222,0.012247,0.273985,0.063119,0.0,0.063315,0.0,0.060613,0.057567,0.037056,0.097885,0.013692,0.091132,0.022074,0.022355,0.019996,0.084996,0.119738,0.202210,0.900764,0.616466,1.870422,7.867253e+05,1.532479e+06,9.629957e+05,9.436459e+05,1.045695e+06,9.799184e+05,1.020234e+06,9.879388e+05,9.876353e+05,5.910309e+05,1.408777e+06,1.603987e+06,1.450466e+06,1.448604e+06,9.136955e+05,1.032707e+06,1.061547e+06,1.038200e+06,1.038228e+06,6.177332e+05,4.878595e+05,1.069981e+06,6.468916e+05,6.347972e+05,8.759596e+05,3.938363e+05,3.992241e+05,3.952172e+05,3.953117e+05,1.067968e+05,27.252719,48.743800,31.917304,30.435153,33.642845,2.017726,2.025915,2.019739,2.019739,0.376109,47.606494,59.910929,50.243268,49.674589,44.135107,2.132174,2.134751,2.132799,2.132799,0.259850,13.510661,17.965303,14.750808,14.750808,12.282050,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.486569e-05,0.0,26.356657,26.348293,0.0,3.459396e+02,3.457120
min,100002.000000,0.000000,0.000000,2.610000e+04,4.500000e+04,1980.000000,4.050000e+04,0.000533,-25187.00000,-17531.000000,-23738.000000,-6274.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.014691,0.000005,0.000527,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4026.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.054545,0.0,0.0,0.0,0.0,0.000000e+00,0.0,1.000000,1.000000,1.0,2.018010e+07,201801.000000
25%,189175.750000,0.000000,0.000000,1.125000e+05,2.700000e+05,16573.500000,2.385000e+05,0.010006,-19690.25000,-2747.000000,-7461.250000,-4299.000000,5.000000,1.0,1.000000,0.000000,1.000000,0.000000,0.000000,2.000000,2.000000,2.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.332962,0.393108,0.370650,0.057700,0.043600,0.976700,0.687200,0.007900,0.000000,0.069000,0.166700,0.083300,0.018600,0.050400,0.045100,0.000000,0.000000,0.052500,0.040000,0.976700,0.699400,0.007200,0.000000,0.069000,0.166700,0.083300,0.016400,0.054200,0.042400,0.000000,0.000000,0.058300,0.043100,0.976700,0.691400,0.007900,0.000000,0.069000,0.166700,0.083300,0.018600,0.051300,0.045500,0.000000,0.000000,0.041000,0.000000,0.000000,0.000000,0.000000,-1571.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.978559e+04,9.211950e+04,7.493285e+04,6.741000e+04,4.820168e+04,5.170059e+04,6.299888e+04,5.961818e+04,5.888812e+04,1.272792e+04,6.750000e+04,1.125000e+05,1.024746e+05,9.821138e+04,6.714480e+04,6.639975e+04,6.750000e+04,6.750000e+04,6.750000e+04,2.606678e+04,3.045533e+04,6.430669e+04,5.463765e+04,5.025258e+04,2.822233e+04,1.458211e+04,1.800000e+04,1.800000e+04,1.800000e+04,4.677412e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.243324,0.198645,0.500000,0.0,0.0,0.0,0.0,0.000000e+00,0.0,15.000000,15.000000,1.0,2.018040e+07,201804.000000
50%,278856.500000,0.000000,0.000000,1.485000e+05,5.135310e+05,24939.000000,4.500000e+05,0.018850,-15754.00000,-1215.000000,-4502.000000,-3276.000000,9.000000,1.0,1.000000,0.000000,1.000000,0.000000,0.000000,2.000000,2.000000,2.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.505967,0.566539,0.535276,0.087100,0.076200,0.982100,0.755200,0.021000,0.000000,0.137900,0.166700,0.208300,0.048200,0.075600,0.074300,0.000000,0.003500,0.084000,0.074700,0.981600,0.764800,0.019100,0.000000,0.137900,0.166700,0.208300,0.045700,0.075300,0.073000,0.000000,0.001000,0.086400,0.075800,0.982100,0.758500,0.020800,0.000000,0.137900,0.166700,0.208300,0.048600,0.076100,0.074700,0.000000,0.003000,0.068600,0.000000,0.000000,0.000000,0.000000,-758.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,7.020000e+04,2.250000e+05,1.544850e+05,1.350000e+05,1.256782e+05,1.163790e+05,1.350000e+05,1.305000e+05,1.291500e+05,5.075104e+04,1.575000e+05,2.602744e+05,2.250000e+05,2.250000e+05,1.750089e+05,1.350000e+05,1.360689e+05,1.350000e+05,1.350000e+05,7.474472e+04,6.615000e+04,1.350000e+05,1.073923e+05,9.859500e+04,7.387922e+04,2.948850e+04,3.600000e+04,3.375000e+04,3.375000e+04,6.363961e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.707551,0.564197,0.961004,0.0,0.0,0.0,0.0,0.000000e+00,0.0,31.000000,31.000000,1.0,2.018070e+07,201807.000000
75%,366960.000000,0.000000,0.000000,2.025000e+05,8.086500e+05,34644.375000,6.795000e+05,0.028663,-12394.00000,-291.000000,-2015.000000,-1732.000000,15.000000,1.0,1.000000,0.000000,1.000000,1.000000,0.000000,3.000000,2.000000,2.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.673425,0.664295,0.669057,0.148500,0.112600,0.986600,0.823200,0.052100,0.120000,0.206900,0.333300,0.375000,0.086000,0.121000,0.130300,0.003900,0.027600,0.145000,0.112900,0.986600,0.823600,0.049500,0.120800,0.206900,0.333300,0.375000,0.084500,0.131300,0.125700,0.003900,0.023000,0.149525,0.112100,0.986600,0.825600,0.052000,0.120000,0.206900,0.333300,0.375000,0.087200,0.123100,0.130900,0.003900,0.026700,0.128400,2.000000,0.000000,2.000000,0.000000,-276.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,1.696285e+05,5.490000e+05,3.510836e+05,2.925000e+05,3.302886e+05,2.841705e+05,3.503419e+05,3.230938e+05,3.199056e+05,1.664112e+05,4.117725e+05,6.614662e+05,5.265000e+05,5.101200e+05,4.454773e+05,3.342060e+05,3.836070e+05,3.600000e+05,3.600000e+05,2.227386e+05,1.387935e+05,3.150000e+05,2.283491e+05,2.237558e+05,1.999448e+05,9.000000e+04,9.174407e+04,9.000000e+04,9.000000e+04,1.304371e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.795717,1.642841,1.266447,0.0,0.0,0.0,0.0,0.000000e+00,0.0,54.000000,54.000000,1.0,2.018100e+07,201810.000000
max,456251.000000,1.000000,12.000000,1.350000e+07,4.050000e+06,225000.000000,4.050000e+06,0.072508,-7489.00000,365243.000000,0.000000,0.000000,65.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,16.000000,3.000000,3.000000,23.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.943982,0.855000,0.893976,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,30.000000,6.000000,29.000000,5.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,9.000000,8.000000,23.000000,19.000000,25.000000,9.207000e+07,1.327500e+08,9.207000e+07,9.207000e+07,9.383661e+07,3.555000e+07,3.555000e+07,3.555000e+07,3.555000e+07,7.243559e+06,1.035000e+08,1.035000e+08,1.035000e+08,1.035000e+08,3.137433e+07,3.555000e+07,3.555000e+07,3.555000e+07,3.555000e+07,7.174122e+06,2.122650e+07,1.327500e+08,6.639750e+07,6.639750e+07,9.383661e+07,7.820595e+06,7.820595e+06,7.820595e+06,7.820595e+06,1.418562e+06,2631.000000,2667.000000,2631.000000,2631.000000,1839.891845,82.000000,82.000000,82.000000,82.000000,9.899495,2631.000000,2667.000000,2631.000000,2631.000000,1839.891845,82.000000,82.000000,82.000000,82.000000,6.363961,1681.000000,1681.000000,1681.000000,1681.000000,1187.939392,0.0,0.0,0.0,0.0,0.0,inf,inf,inf,inf,inf,inf,inf,1.284610e-02,0.0,96.000000,96.000000,1.0,2.018123e+07,201812.000000

In [13]:
# get something desriptive for all variables
data.describe(include='all')

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,MIN_AMTCR_0M_INFM,MAX_AMTCR_0M_INFM,MEAN_AMTCR_0M_INFM,MEDIAN_AMTCR_0M_INFM,STD_AMTCR_0M_INFM,MIN_AMTCR_0M_6M,MAX_AMTCR_0M_6M,MEAN_AMTCR_0M_6M,MEDIAN_AMTCR_0M_6M,STD_AMTCR_0M_6M,MIN_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MAX_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MEAN_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MEDIAN_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,STD_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MIN_AMTCR_0M_6M_TYPE_EQ_ACTIVE,MAX_AMTCR_0M_6M_TYPE_EQ_ACTIVE,MEAN_AMTCR_0M_6M_TYPE_EQ_ACTIVE,MEDIAN_AMTCR_0M_6M_TYPE_EQ_ACTIVE,STD_AMTCR_0M_6M_TYPE_EQ_ACTIVE,MIN_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MAX_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MEAN_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MEDIAN_AMTCR_0M_INFM_TYPE_EQ_CLOSED,STD_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MIN_AMTCR_0M_6M_TYPE_EQ_CLOSED,MAX_AMTCR_0M_6M_TYPE_EQ_CLOSED,MEAN_AMTCR_0M_6M_TYPE_EQ_CLOSED,MEDIAN_AMTCR_0M_6M_TYPE_EQ_CLOSED,STD_AMTCR_0M_6M_TYPE_EQ_CLOSED,MIN_DPD_0M_INFM,MAX_DPD_0M_INFM,MEAN_DPD_0M_INFM,MEDIAN_DPD_0M_INFM,STD_DPD_0M_INFM,MIN_DPD_0M_6M,MAX_DPD_0M_6M,MEAN_DPD_0M_6M,MEDIAN_DPD_0M_6M,STD_DPD_0M_6M,MIN_DPD_0M_INFM_TYPE_EQ_ACTIVE,MAX_DPD_0M_INFM_TYPE_EQ_ACTIVE,MEAN_DPD_0M_INFM_TYPE_EQ_ACTIVE,MEDIAN_DPD_0M_INFM_TYPE_EQ_ACTIVE,STD_DPD_0M_INFM_TYPE_EQ_ACTIVE,MIN_DPD_0M_6M_TYPE_EQ_ACTIVE,MAX_DPD_0M_6M_TYPE_EQ_ACTIVE,MEAN_DPD_0M_6M_TYPE_EQ_ACTIVE,MEDIAN_DPD_0M_6M_TYPE_EQ_ACTIVE,STD_DPD_0M_6M_TYPE_EQ_ACTIVE,MIN_DPD_0M_INFM_TYPE_EQ_CLOSED,MAX_DPD_0M_INFM_TYPE_EQ_CLOSED,MEAN_DPD_0M_INFM_TYPE_EQ_CLOSED,MEDIAN_DPD_0M_INFM_TYPE_EQ_CLOSED,STD_DPD_0M_INFM_TYPE_EQ_CLOSED,MIN_DPD_0M_6M_TYPE_EQ_CLOSED,MAX_DPD_0M_6M_TYPE_EQ_CLOSED,MEAN_DPD_0M_6M_TYPE_EQ_CLOSED,MEDIAN_DPD_0M_6M_TYPE_EQ_CLOSED,STD_DPD_0M_6M_TYPE_EQ_CLOSED,MEAN_AMTCR_1M_3M_DIV_MEAN_AMTCR_3M_12M,MEAN_AMTCR_1M_3M_TYPE_EQ_ACTIVE_DIV_MEAN_AMTCR_3M_12M_TYPE_EQ_ACTIVE,MEAN_AMTCR_1M_3M_TYPE_EQ_CLOSED_DIV_MEAN_AMTCR_3M_12M_TYPE_EQ_CLOSED,MEAN_AMTCR_OVERDUE_0M_INFM_DIV_MEAN_AMTCR_0M_INFM,MEAN_AMTCR_OVERDUE_0M_12M_DIV_MEAN_AMTCR_0M_12M,MEAN_AMTCR_OVERDUE_0M_INFM_TYPE_EQ_ACTIVE_DIV_MEAN_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MEAN_AMTCR_OVERDUE_0M_12M_TYPE_EQ_ACTIVE_DIV_MEAN_AMTCR_0M_12M_TYPE_EQ_ACTIVE,MEAN_AMTCR_OVERDUE_0M_INFM_TYPE_EQ_CLOSED_DIV_MEAN_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MEAN_AMTCR_OVERDUE_0M_12M_TYPE_EQ_CLOSED_DIV_MEAN_AMTCR_0M_12M_TYPE_EQ_CLOSED,FIRST_TRANSACTION_TIME_MONTHS,LAST_TRANSACTION_TIME_MONTHS,TIME,BASE,DAY,MONTH
count,80000.000000,80000.000000,80000,80000,80000,80000,55035.000000,8.000000e+04,8.000000e+04,79994.000000,7.993700e+04,79647,80000,80000,80000,80000,80000.000000,59780.00000,80000.000000,80000.000000,80000.000000,27316.000000,80000.0,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,54933,80000.000000,80000.000000,80000.000000,80000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000,34846.000000,79830.000000,64067.000000,39464.000000,33183.000000,40971.000000,26643.000000,23938.000000,37415.000000,39744.000000,40221.000000,25594.000000,32469.000000,25225.000000,39861.000000,24335.000000,35892.000000,39464.000000,33183.000000,40971.000000,26643.000000,23938.000000,37415.000000,39744.000000,40221.000000,25594.000000,32469.000000,25225.000000,39861.000000,24335.000000,35892.000000,39464.000000,33183.000000,40971.000000,26643.000000,23938.000000,37415.000000,39744.000000,40221.000000,25594.000000,32469.000000,25225.000000,39861.000000,24335.000000,35892.000000,25114,39880,41413.000000,39374,42108,79733.000000,79733.000000,79733.000000,79733.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.0,80000.000000,80000.0,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,69202.000000,69202.000000,69202.000000,69202.000000,69202.000000,69202.000000,4.964700e+04,4.964700e+04,4.964700e+04,4.964700e+04,2.863600e+04,8.332000e+03,8.332000e+03,8.332000e+03,8.332000e+03,9.920000e+02,2.946000e+04,2.946000e+04,2.946000e+04,2.946000e+04,8.692000e+03,7.502000e+03,7.502000e+03,7.502000e+03,7.502000e+03,6.290000e+02,3.774700e+04,3.774700e+04,3.774700e+04,3.774700e+04,1.754500e+04,1.123000e+03,1.123000e+03,1.123000e+03,1.123000e+03,2.000000e+02,49647.000000,49647.000000,49647.000000,49647.000000,28636.000000,8332.000000,8332.000000,8332.000000,8332.000000,992.000000,29460.000000,29460.000000,29460.000000,29460.000000,8692.000000,7502.000000,7502.000000,7502.000000,7502.000000,629.000000,37747.000000,37747.000000,37747.000000,37747.000000,17545.000000,1123.0,1123.0,1123.0,1123.0,200.0,826.000000,480.000000,136.000000,48910.0,16914.0,28407.0,14243.0,3.715600e+04,3833.0,49647.000000,49647.000000,80000,80000.0,8.000000e+04,80000.000000
unique,NaN,NaN,2,3,2,2,NaN,NaN,NaN,NaN,NaN,7,7,5,5,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18,NaN,NaN,NaN,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,3,NaN,7,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,365,NaN,NaN,NaN
top,NaN,NaN,Cash loans,F,N,Y,NaN,NaN,NaN,NaN,NaN,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Laborers,NaN,NaN,NaN,TUESDAY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Business Entity Type 3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,reg oper account,block of flats,NaN,Panel,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-02-01,NaN,NaN,NaN
freq,NaN,NaN,72366,52488,52682,55485,NaN,NaN,NaN,NaN,NaN,64664,41321,56902,51144,71019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14344,NaN,NaN,NaN,14031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17826,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18999,39216,NaN,17165,41513,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,266,NaN,NaN,NaN
mean,278160.918850,0.080200,NaN,NaN,NaN,NaN,0.324648,1.682663e+05,5.982419e+05,27115.320924,5.376062e+05,NaN,NaN,NaN,NaN,NaN,0.020899,-16031.07740,63636.234238,-4978.924851,-3001.864075,12.091119,1.0,0.820400,0.198625,0.998250,0.283100,0.055875,NaN,2.154425,2.050687,2.031062,NaN,12.072000,0.015200,0.050700,0.040750,0.079175,0.231988,0.180638,NaN,0.501278,0.514797,0.511271,0.117545,0.088836,0.977852,0.752290,0.044937,0.079072,0.150143,0.225410,0.232124,0.065884,0.101017,0.107678,0.008634,0.028316,0.114319,0.087858,0.977251,0.759385,0.042826,0.074590,0.145539,0.221589,0.228336,0.064436,0.105748,0.106196,0.007910,0.027049,0.117961,0.088312,0.977882,0.755542,0.044898,0.078174,0.149642,0.225014,0.231878,0.066722,0.102156,0.108885,0.008481,0.028289,NaN,NaN,0.102511,NaN,NaN,1.414621,0.143002,1.397928,0.098692,-964.726887,0.000050,0.709075,0.000150,0.014762,0.088637,0.000150,0.081750,0.004000,0.0,0.004025,0.0,0.003687,0.003325,0.001375,0.009675,0.000188,0.008375,0.000487,0.000500,0.000400,0.006662,0.007456,0.033019,0.265961,0.265050,1.898876,2.174489e+05,5.730609e+05,3.612088e+05,3.244880e+05,3.403966e+05,3.630318e+05,4.004173e+05,3.812033e+05,3.803529e+05,2.148186e+05,4.521546e+05,6.526904e+05,5.462184e+05,5.364440e+05,4.413954e+05,3.956119e+05,4.263778e+05,4.108470e+05,4.105890e+05,2.551735e+05,1.756302e+05,3.453890e+05,2.484649e+05,2.342851e+05,2.112701e+05,1.332824e+05,1.399345e+05,1.365120e+05,1.364546e+05,2.463133e+04,0.424980,1.440349,0.818269,0.650946,1.082080,0.100816,0.103817,0.102316,0.102316,0.017820,1.332043,2.163103,1.695063,1.599321,1.849370,0.113836,0.115303,0.114569,0.114569,0.012366,0.120063,0.206215,0.163139,0.163139,0.131064,0.0,0.0,0.0,0.0,0.0,inf,inf,inf,inf,inf,inf,inf,6.318908e-07,0.0,36.875904,36.835841,NaN,1.0,2.018067e+07,201806.523287
std,102712.983646,0.271604,NaN,NaN,NaN,NaN,0.637932,1.092775e+05,4.002051e+05,14471.545555,3.674006e+05,NaN,NaN,NaN,NaN,NaN,0.013846,4365.52899,141122.463859,3514.337620,1506.200651,11.990588,0.0,0.383856,0.398968,0.041797,0.450507,0.229682,NaN,0.910007,0.509383,0.503191,NaN,3.274492,0.122348,0.219386,0.197712,0.270013,0.422104,0.384720,NaN,0.210864,0.191141,0.194762,0.107710,0.083747,0.058457,0.111862,0.076364,0.134956,0.100020,0.144488,0.161035,0.079140,0.092739,0.110752,0.047427,0.069154,0.107680,0.085682,0.063114,0.108773,0.074788,0.132909,0.100995,0.143752,0.160770,0.079852,0.097733,0.112075,0.045836,0.070336,0.108671,0.083402,0.059210,0.110681,0.076563,0.134902,0.100352,0.144937,0.161593,0.080229,0.093791,0.112493,0.047284,0.070028,NaN,NaN,0.107099,NaN,NaN,2.327886,0.442464,2.307764,0.355815,828.199522,0.007071,0.454192,0.012247,0.120602,0.284222,0.012247,0.273985,0.063119,0.0,0.063315,0.0,0.060613,0.057567,0.037056,0.097885,0.013692,0.091132,0.022074,0.022355,0.019996,0.084996,0.119738,0.202210,0.900764,0.616466,1.870422,7.867253e+05,1.532479e+06,9.629957e+05,9.436459e+05,1.045695e+06,9.799184e+05,1.020234e+06,9.879388e+05,9.876353e+05,5.910309e+05,1.408777e+06,1.603987e+06,1.450466e+06,1.448604e+06,9.136955e+05,1.032707e+06,1.061547e+06,1.038200e+06,1.038228e+06,6.177332e+05,4.878595e+05,1.069981e+06,6.468916e+05,6.347972e+05,8.759596e+05,3.938363e+05,3.992241e+05,3.952172e+05,3.953117e+05,1.067968e+05,27.252719,48.743800,31.917304,30.435153,33.642845,2.017726,2.025915,2.019739,2.019739,0.376109,47.606494,59.910929,50.243268,49.674589,44.135107,2.132174,2.134751,2.132799,2.132799,0.259850,13.510661,17.965303,14.750808,14.750808,12.282050,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.486569e-05,0.0,26.356657,26.348293,NaN,0.0,3.459396e+02,3.457120
min,100002.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,2.610000e+04,4.500000e+04,1980.000000,4.050000e+04,NaN,NaN,NaN,NaN,NaN,0.000533,-25187.00000,-17531.000000,-23738.000000,-6274.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,1.000000,1.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.014691,0.000005,0.000527,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,-4026.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.054545,0.0,0.0,0.0,0.0,0.000000e+00,0.0,1.000000,1.000000,NaN,1.0,2.018010e+07,201801.000000
25%,189175.750000,0.000000,NaN,NaN,NaN,NaN,0.000000,1.125000e+05,2.700000e+05,16573.500000,2.385000e+05,NaN,NaN,NaN,NaN,NaN,0.010006,-19690.25000,-2747.000000,-7461.250000,-4299.000000,5.000000,1.0,1.000000,0.000000,1.000000,0.000000,0.000000,NaN,2.000000,2.000000,2.000000,NaN,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.332962,0.393108,0.370650,0.057700,0.043600,0.976700,0.687200,0.007900,0.000000,0.069000,0.166700,0.083300,0.018600,0.050400,0.045100,0.000000,0.000000,0.052500,0.040000,0.976700,0.699400,0.007200,0.000000,0.069000,0.166700,0.083300,0.016400,0.054200,0.042400,0.000000,0.000000,0.058300,0.043100,0.976700,0.691400,0.007900,0.000000,0.069000,0.166700,0.083300,0.018600,0.051300,0.045500,0.000000,0.000000,NaN,NaN,0.041000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,-1571.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.978559e+04,9.211950e+04,7.493285e+04,6.741000e+04,4.820168e+04,5.170059e+04,6.299888e+04,5.961818e+04,5.888812e+04,1.272792e+04,6.750000e+04,1.125000e+05,1.024746e+05,9.821138e+04,6.714480e+04,6.639975e+04,6.750000e+04,6.750000e+04,6.750000e+04,2.606678e+04,3.045533e+04,6.430669e+04,5.463765e+04,5.025258e+04,2.822233e+04,1.458211e+04,1.800000e+04,1.800000e+04,1.800000e+04,4.677412e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.243324,0.198645,0.500000,0.0,0.0,0.0,0.0,0.000000e+00,0.0,15.000000,15.000000,NaN,1.0,2.018040e+07,201804.000000
50%,278856.500000,0.000000,NaN,NaN,NaN,NaN,0.000000,1.485000e+05,5.135310e+05,24939.000000,4.500000e+05,NaN,NaN,NaN,NaN,NaN,0.018850,-15754.00000,-1215.000000,-4502.000000,-3276.000000,9.000000,1.0,1.000000,0.000000,1.000000,0.000000,0.000000,NaN,2.000000,2.000000,2.000000,NaN,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.505967,0.566539,0.535276,0.087100,0.076200,0.982100,0.755200,0.021000,0.000000,0.137900,0.166700,0.208300,0.048200,0.075600,0.074300,0.000000,0.003500,0.084000,0.074700,0.981600,0.764800,0.019100,0.000000,0.137900,0.166700,0.208300,0.045700,0.075300,0.073000,0.000000,0.001000,0.086400,0.075800,0.982100,0.758500,0.020800,0.000000,0.137900,0.166700,0.208300,0.048600,0.076100,0.074700,0.000000,0.003000,NaN,NaN,0.068600,NaN,NaN,0.000000,0.000000,0.000000,0.000000,-758.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,7.020000e+04,2.250000e+05,1.544850e+05,1.350000e+05,1.256782e+05,1.163790e+05,1.350000e+05,1.305000e+05,1.291500e+05,5.075104e+04,1.575000e+05,2.602744e+05,2.250000e+05,2.250000e+05,1.750089e+05,1.350000e+05,1.360689e+05,1.350000e+05,1.350000e+05,7.474472e+04,6.615000e+04,1.350000e+05,1.073923e+05,9.859500e+04,7.387922e+04,2.948850e+04,3.600000e+04,3.375000e+04,3.375000e+04,6.363961e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.707551,0.564197,0.961004,0.0,0.0,0.0,0.0,0.000000e+00,0.0,31.000000,31.000000,NaN,1.0,2.018070e+07,201807.000000

In [14]:
# column data types
data.dtypes

SK_ID_CURR                        int64
TARGET                          float64
NAME_CONTRACT_TYPE               object
CODE_GENDER                      object
FLAG_OWN_CAR                     object
                                 ...
LAST_TRANSACTION_TIME_MONTHS    float64
TIME                             object
BASE                              int64
DAY                               int64
MONTH                             int64
Length: 197, dtype: object

In [15]:
# define list of numerical predictors
cols_num = [col for col in data.columns if data[col].dtype != 'O']
# define list of categorical predictors
cols_cat = [col for col in data.columns if data[col].dtype == 'O']

In [16]:
data[cols_num].describe()

,SK_ID_CURR,TARGET,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,TOTALAREA_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,MIN_AMTCR_0M_INFM,MAX_AMTCR_0M_INFM,MEAN_AMTCR_0M_INFM,MEDIAN_AMTCR_0M_INFM,STD_AMTCR_0M_INFM,MIN_AMTCR_0M_6M,MAX_AMTCR_0M_6M,MEAN_AMTCR_0M_6M,MEDIAN_AMTCR_0M_6M,STD_AMTCR_0M_6M,MIN_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MAX_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MEAN_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MEDIAN_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,STD_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MIN_AMTCR_0M_6M_TYPE_EQ_ACTIVE,MAX_AMTCR_0M_6M_TYPE_EQ_ACTIVE,MEAN_AMTCR_0M_6M_TYPE_EQ_ACTIVE,MEDIAN_AMTCR_0M_6M_TYPE_EQ_ACTIVE,STD_AMTCR_0M_6M_TYPE_EQ_ACTIVE,MIN_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MAX_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MEAN_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MEDIAN_AMTCR_0M_INFM_TYPE_EQ_CLOSED,STD_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MIN_AMTCR_0M_6M_TYPE_EQ_CLOSED,MAX_AMTCR_0M_6M_TYPE_EQ_CLOSED,MEAN_AMTCR_0M_6M_TYPE_EQ_CLOSED,MEDIAN_AMTCR_0M_6M_TYPE_EQ_CLOSED,STD_AMTCR_0M_6M_TYPE_EQ_CLOSED,MIN_DPD_0M_INFM,MAX_DPD_0M_INFM,MEAN_DPD_0M_INFM,MEDIAN_DPD_0M_INFM,STD_DPD_0M_INFM,MIN_DPD_0M_6M,MAX_DPD_0M_6M,MEAN_DPD_0M_6M,MEDIAN_DPD_0M_6M,STD_DPD_0M_6M,MIN_DPD_0M_INFM_TYPE_EQ_ACTIVE,MAX_DPD_0M_INFM_TYPE_EQ_ACTIVE,MEAN_DPD_0M_INFM_TYPE_EQ_ACTIVE,MEDIAN_DPD_0M_INFM_TYPE_EQ_ACTIVE,STD_DPD_0M_INFM_TYPE_EQ_ACTIVE,MIN_DPD_0M_6M_TYPE_EQ_ACTIVE,MAX_DPD_0M_6M_TYPE_EQ_ACTIVE,MEAN_DPD_0M_6M_TYPE_EQ_ACTIVE,MEDIAN_DPD_0M_6M_TYPE_EQ_ACTIVE,STD_DPD_0M_6M_TYPE_EQ_ACTIVE,MIN_DPD_0M_INFM_TYPE_EQ_CLOSED,MAX_DPD_0M_INFM_TYPE_EQ_CLOSED,MEAN_DPD_0M_INFM_TYPE_EQ_CLOSED,MEDIAN_DPD_0M_INFM_TYPE_EQ_CLOSED,STD_DPD_0M_INFM_TYPE_EQ_CLOSED,MIN_DPD_0M_6M_TYPE_EQ_CLOSED,MAX_DPD_0M_6M_TYPE_EQ_CLOSED,MEAN_DPD_0M_6M_TYPE_EQ_CLOSED,MEDIAN_DPD_0M_6M_TYPE_EQ_CLOSED,STD_DPD_0M_6M_TYPE_EQ_CLOSED,MEAN_AMTCR_1M_3M_DIV_MEAN_AMTCR_3M_12M,MEAN_AMTCR_1M_3M_TYPE_EQ_ACTIVE_DIV_MEAN_AMTCR_3M_12M_TYPE_EQ_ACTIVE,MEAN_AMTCR_1M_3M_TYPE_EQ_CLOSED_DIV_MEAN_AMTCR_3M_12M_TYPE_EQ_CLOSED,MEAN_AMTCR_OVERDUE_0M_INFM_DIV_MEAN_AMTCR_0M_INFM,MEAN_AMTCR_OVERDUE_0M_12M_DIV_MEAN_AMTCR_0M_12M,MEAN_AMTCR_OVERDUE_0M_INFM_TYPE_EQ_ACTIVE_DIV_MEAN_AMTCR_0M_INFM_TYPE_EQ_ACTIVE,MEAN_AMTCR_OVERDUE_0M_12M_TYPE_EQ_ACTIVE_DIV_MEAN_AMTCR_0M_12M_TYPE_EQ_ACTIVE,MEAN_AMTCR_OVERDUE_0M_INFM_TYPE_EQ_CLOSED_DIV_MEAN_AMTCR_0M_INFM_TYPE_EQ_CLOSED,MEAN_AMTCR_OVERDUE_0M_12M_TYPE_EQ_CLOSED_DIV_MEAN_AMTCR_0M_12M_TYPE_EQ_CLOSED,FIRST_TRANSACTION_TIME_MONTHS,LAST_TRANSACTION_TIME_MONTHS,BASE,DAY,MONTH
count,80000.000000,80000.000000,55035.000000,8.000000e+04,8.000000e+04,79994.000000,7.993700e+04,80000.000000,59780.00000,80000.000000,80000.000000,80000.000000,27316.000000,80000.0,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,34846.000000,79830.000000,64067.000000,39464.000000,33183.000000,40971.000000,26643.000000,23938.000000,37415.000000,39744.000000,40221.000000,25594.000000,32469.000000,25225.000000,39861.000000,24335.000000,35892.000000,39464.000000,33183.000000,40971.000000,26643.000000,23938.000000,37415.000000,39744.000000,40221.000000,25594.000000,32469.000000,25225.000000,39861.000000,24335.000000,35892.000000,39464.000000,33183.000000,40971.000000,26643.000000,23938.000000,37415.000000,39744.000000,40221.000000,25594.000000,32469.000000,25225.000000,39861.000000,24335.000000,35892.000000,41413.000000,79733.000000,79733.000000,79733.000000,79733.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.0,80000.000000,80000.0,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,69202.000000,69202.000000,69202.000000,69202.000000,69202.000000,69202.000000,4.964700e+04,4.964700e+04,4.964700e+04,4.964700e+04,2.863600e+04,8.332000e+03,8.332000e+03,8.332000e+03,8.332000e+03,9.920000e+02,2.946000e+04,2.946000e+04,2.946000e+04,2.946000e+04,8.692000e+03,7.502000e+03,7.502000e+03,7.502000e+03,7.502000e+03,6.290000e+02,3.774700e+04,3.774700e+04,3.774700e+04,3.774700e+04,1.754500e+04,1.123000e+03,1.123000e+03,1.123000e+03,1.123000e+03,2.000000e+02,49647.000000,49647.000000,49647.000000,49647.000000,28636.000000,8332.000000,8332.000000,8332.000000,8332.000000,992.000000,29460.000000,29460.000000,29460.000000,29460.000000,8692.000000,7502.000000,7502.000000,7502.000000,7502.000000,629.000000,37747.000000,37747.000000,37747.000000,37747.000000,17545.000000,1123.0,1123.0,1123.0,1123.0,200.0,826.000000,480.000000,136.000000,48910.0,16914.0,28407.0,14243.0,3.715600e+04,3833.0,49647.000000,49647.000000,80000.0,8.000000e+04,80000.000000
mean,278160.918850,0.080200,0.324648,1.682663e+05,5.982419e+05,27115.320924,5.376062e+05,0.020899,-16031.07740,63636.234238,-4978.924851,-3001.864075,12.091119,1.0,0.820400,0.198625,0.998250,0.283100,0.055875,2.154425,2.050687,2.031062,12.072000,0.015200,0.050700,0.040750,0.079175,0.231988,0.180638,0.501278,0.514797,0.511271,0.117545,0.088836,0.977852,0.752290,0.044937,0.079072,0.150143,0.225410,0.232124,0.065884,0.101017,0.107678,0.008634,0.028316,0.114319,0.087858,0.977251,0.759385,0.042826,0.074590,0.145539,0.221589,0.228336,0.064436,0.105748,0.106196,0.007910,0.027049,0.117961,0.088312,0.977882,0.755542,0.044898,0.078174,0.149642,0.225014,0.231878,0.066722,0.102156,0.108885,0.008481,0.028289,0.102511,1.414621,0.143002,1.397928,0.098692,-964.726887,0.000050,0.709075,0.000150,0.014762,0.088637,0.000150,0.081750,0.004000,0.0,0.004025,0.0,0.003687,0.003325,0.001375,0.009675,0.000188,0.008375,0.000487,0.000500,0.000400,0.006662,0.007456,0.033019,0.265961,0.265050,1.898876,2.174489e+05,5.730609e+05,3.612088e+05,3.244880e+05,3.403966e+05,3.630318e+05,4.004173e+05,3.812033e+05,3.803529e+05,2.148186e+05,4.521546e+05,6.526904e+05,5.462184e+05,5.364440e+05,4.413954e+05,3.956119e+05,4.263778e+05,4.108470e+05,4.105890e+05,2.551735e+05,1.756302e+05,3.453890e+05,2.484649e+05,2.342851e+05,2.112701e+05,1.332824e+05,1.399345e+05,1.365120e+05,1.364546e+05,2.463133e+04,0.424980,1.440349,0.818269,0.650946,1.082080,0.100816,0.103817,0.102316,0.102316,0.017820,1.332043,2.163103,1.695063,1.599321,1.849370,0.113836,0.115303,0.114569,0.114569,0.012366,0.120063,0.206215,0.163139,0.163139,0.131064,0.0,0.0,0.0,0.0,0.0,inf,inf,inf,inf,inf,inf,inf,6.318908e-07,0.0,36.875904,36.835841,1.0,2.018067e+07,201806.523287
std,102712.983646,0.271604,0.637932,1.092775e+05,4.002051e+05,14471.545555,3.674006e+05,0.013846,4365.52899,141122.463859,3514.337620,1506.200651,11.990588,0.0,0.383856,0.398968,0.041797,0.450507,0.229682,0.910007,0.509383,0.503191,3.274492,0.122348,0.219386,0.197712,0.270013,0.422104,0.384720,0.210864,0.191141,0.194762,0.107710,0.083747,0.058457,0.111862,0.076364,0.134956,0.100020,0.144488,0.161035,0.079140,0.092739,0.110752,0.047427,0.069154,0.107680,0.085682,0.063114,0.108773,0.074788,0.132909,0.100995,0.143752,0.160770,0.079852,0.097733,0.112075,0.045836,0.070336,0.108671,0.083402,0.059210,0.110681,0.076563,0.134902,0.100352,0.144937,0.161593,0.080229,0.093791,0.112493,0.047284,0.070028,0.107099,2.327886,0.442464,2.307764,0.355815,828.199522,0.007071,0.454192,0.012247,0.120602,0.284222,0.012247,0.273985,0.063119,0.0,0.063315,0.0,0.060613,0.057567,0.037056,0.097885,0.013692,0.091132,0.022074,0.022355,0.019996,0.084996,0.119738,0.202210,0.900764,0.616466,1.870422,7.867253e+05,1.532479e+06,9.629957e+05,9.436459e+05,1.045695e+06,9.799184e+05,1.020234e+06,9.879388e+05,9.876353e+05,5.910309e+05,1.408777e+06,1.603987e+06,1.450466e+06,1.448604e+06,9.136955e+05,1.032707e+06,1.061547e+06,1.038200e+06,1.038228e+06,6.177332e+05,4.878595e+05,1.069981e+06,6.468916e+05,6.347972e+05,8.759596e+05,3.938363e+05,3.992241e+05,3.952172e+05,3.953117e+05,1.067968e+05,27.252719,48.743800,31.917304,30.435153,33.642845,2.017726,2.025915,2.019739,2.019739,0.376109,47.606494,59.910929,50.243268,49.674589,44.135107,2.132174,2.134751,2.132799,2.132799,0.259850,13.510661,17.965303,14.750808,14.750808,12.282050,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.486569e-05,0.0,26.356657,26.348293,0.0,3.459396e+02,3.457120
min,100002.000000,0.000000,0.000000,2.610000e+04,4.500000e+04,1980.000000,4.050000e+04,0.000533,-25187.00000,-17531.000000,-23738.000000,-6274.000000,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.014691,0.000005,0.000527,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4026.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.054545,0.0,0.0,0.0,0.0,0.000000e+00,0.0,1.000000,1.000000,1.0,2.018010e+07,201801.000000
25%,189175.750000,0.000000,0.000000,1.125000e+05,2.700000e+05,16573.500000,2.385000e+05,0.010006,-19690.25000,-2747.000000,-7461.250000,-4299.000000,5.000000,1.0,1.000000,0.000000,1.000000,0.000000,0.000000,2.000000,2.000000,2.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.332962,0.393108,0.370650,0.057700,0.043600,0.976700,0.687200,0.007900,0.000000,0.069000,0.166700,0.083300,0.018600,0.050400,0.045100,0.000000,0.000000,0.052500,0.040000,0.976700,0.699400,0.007200,0.000000,0.069000,0.166700,0.083300,0.016400,0.054200,0.042400,0.000000,0.000000,0.058300,0.043100,0.976700,0.691400,0.007900,0.000000,0.069000,0.166700,0.083300,0.018600,0.051300,0.045500,0.000000,0.000000,0.041000,0.000000,0.000000,0.000000,0.000000,-1571.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.978559e+04,9.211950e+04,7.493285e+04,6.741000e+04,4.820168e+04,5.170059e+04,6.299888e+04,5.961818e+04,5.888812e+04,1.272792e+04,6.750000e+04,1.125000e+05,1.024746e+05,9.821138e+04,6.714480e+04,6.639975e+04,6.750000e+04,6.750000e+04,6.750000e+04,2.606678e+04,3.045533e+04,6.430669e+04,5.463765e+04,5.025258e+04,2.822233e+04,1.458211e+04,1.800000e+04,1.800000e+04,1.800000e+04,4.677412e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.243324,0.198645,0.500000,0.0,0.0,0.0,0.0,0.000000e+00,0.0,15.000000,15.000000,1.0,2.018040e+07,201804.000000
50%,278856.500000,0.000000,0.000000,1.485000e+05,5.135310e+05,24939.000000,4.500000e+05,0.018850,-15754.00000,-1215.000000,-4502.000000,-3276.000000,9.000000,1.0,1.000000,0.000000,1.000000,0.000000,0.000000,2.000000,2.000000,2.000000,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.505967,0.566539,0.535276,0.087100,0.076200,0.982100,0.755200,0.021000,0.000000,0.137900,0.166700,0.208300,0.048200,0.075600,0.074300,0.000000,0.003500,0.084000,0.074700,0.981600,0.764800,0.019100,0.000000,0.137900,0.166700,0.208300,0.045700,0.075300,0.073000,0.000000,0.001000,0.086400,0.075800,0.982100,0.758500,0.020800,0.000000,0.137900,0.166700,0.208300,0.048600,0.076100,0.074700,0.000000,0.003000,0.068600,0.000000,0.000000,0.000000,0.000000,-758.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,7.020000e+04,2.250000e+05,1.544850e+05,1.350000e+05,1.256782e+05,1.163790e+05,1.350000e+05,1.305000e+05,1.291500e+05,5.075104e+04,1.575000e+05,2.602744e+05,2.250000e+05,2.250000e+05,1.750089e+05,1.350000e+05,1.360689e+05,1.350000e+05,1.350000e+05,7.474472e+04,6.615000e+04,1.350000e+05,1.073923e+05,9.859500e+04,7.387922e+04,2.948850e+04,3.600000e+04,3.375000e+04,3.375000e+04,6.363961e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.707551,0.564197,0.961004,0.0,0.0,0.0,0.0,0.000000e+00,0.0,31.000000,31.000000,1.0,2.018070e+07,201807.000000
75%,366960.000000,0.000000,0.000000,2.025000e+05,8.086500e+05,34644.375000,6.795000e+05,0.028663,-12394.00000,-291.000000,-2015.000000,-1732.000000,15.000000,1.0,1.000000,0.000000,1.000000,1.000000,0.000000,3.000000,2.000000,2.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.673425,0.664295,0.669057,0.148500,0.112600,0.986600,0.823200,0.052100,0.120000,0.206900,0.333300,0.375000,0.086000,0.121000,0.130300,0.003900,0.027600,0.145000,0.112900,0.986600,0.823600,0.049500,0.120800,0.206900,0.333300,0.375000,0.084500,0.131300,0.125700,0.003900,0.023000,0.149525,0.112100,0.986600,0.825600,0.052000,0.120000,0.206900,0.333300,0.375000,0.087200,0.123100,0.130900,0.003900,0.026700,0.128400,2.000000,0.000000,2.000000,0.000000,-276.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,1.696285e+05,5.490000e+05,3.510836e+05,2.925000e+05,3.302886e+05,2.841705e+05,3.503419e+05,3.230938e+05,3.199056e+05,1.664112e+05,4.117725e+05,6.614662e+05,5.265000e+05,5.101200e+05,4.454773e+05,3.342060e+05,3.836070e+05,3.600000e+05,3.600000e+05,2.227386e+05,1.387935e+05,3.150000e+05,2.283491e+05,2.237558e+05,1.999448e+05,9.000000e+04,9.174407e+04,9.000000e+04,9.000000e+04,1.304371e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,1.795717,1.642841,1.266447,0.0,0.0,0.0,0.0,0.000000e+00,0.0,54.000000,54.000000,1.0,2.018100e+07,201810.000000
max,456251.000000,1.000000,12.000000,1.350000e+07,4.050000e+06,225000.000000,4.050000e+06,0.072508,-7489.00000,365243.000000,0.000000,0.000000,65.000000,1.0,1.000000,1.000000,1.000000,1.000000,1.000000,16.000000,3.000000,3.000000,23.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.943982,0.855000,0.893976,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,30.000000,6.000000,29.000000,5.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,9.000000,8.000000,23.000000,19.000000,25.000000,9.207000e+07,1.327500e+08,9.207000e+07,9.207000e+07,9.383661e+07,3.555000e+07,3.555000e+07,3.555000e+07,3.555000e+07,7.243559e+06,1.035000e+08,1.035000e+08,1.035000e+08,1.035000e+08,3.137433e+07,3.555000e+07,3.555000e+07,3.555000e+07,3.555000e+07,7.174122e+06,2.122650e+07,1.327500e+08,6.639750e+07,6.639750e+07,9.383661e+07,7.820595e+06,7.820595e+06,7.820595e+06,7.820595e+06,1.418562e+06,2631.000000,2667.000000,2631.000000,2631.000000,1839.891845,82.000000,82.000000,82.000000,82.000000,9.899495,2631.000000,2667.000000,2631.000000,2631.000000,1839.891845,82.000000,82.000000,82.000000,82.000000,6.363961,1681.000000,1681.000000,1681.000000,1681.000000,1187.939392,0.0,0.0,0.0,0.0,0.0,inf,inf,inf,inf,inf,inf,inf,1.284610e-02,0.0,96.000000,96.000000,1.0,2.018123e+07,201812.000000

In [17]:
data[cols_cat].describe()

,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,OCCUPATION_TYPE,WEEKDAY_APPR_PROCESS_START,ORGANIZATION_TYPE,FONDKAPREMONT_MODE,HOUSETYPE_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,TIME
count,80000,80000,80000,80000,79647,80000,80000,80000,80000,54933,80000,80000,25114,39880,39374,42108,80000
unique,2,3,2,2,7,7,5,5,6,18,7,58,4,3,7,2,365
top,Cash loans,F,N,Y,Unaccompanied,Working,Secondary / secondary special,Married,House / apartment,Laborers,TUESDAY,Business Entity Type 3,reg oper account,block of flats,Panel,No,2018-02-01
freq,72366,52488,52682,55485,64664,41321,56902,51144,71019,14344,14031,17826,18999,39216,17165,41513,266

### Converting data types

In [ ]:
# convert TARGET to int (astype)
print(data['TARGET'].dtype)
data['TARGET'] = data['TARGET'].astype(int)
print(data['TARGET'].dtype)

<span style="color:red">**TO DO:** Convert TIME to datetime.</span>

To see list of format codes go to: https://www.w3schools.com/python/gloss_python_date_format_codes.asp

In [24]:
data['TIME'].loc[0:5]
print(data['TIME'].dtype)
print(type(data['TIME'][0]))
data['TIME'] = pd.to_datetime(data['TIME'], format='%Y-%m-%d')
print(data['TIME'].dtype)
print(type(data['TIME'][0]))

object
<class 'str'>
datetime64[ns]
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

### Filter rows and select columns

#### Filter rows

In [25]:
# filtering by integer position
data.iloc[10:15, 10:15]

,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS
10,135000.0,Unaccompanied,Pensioner,Secondary / secondary special,Single / not married
11,45000.0,Unaccompanied,Pensioner,Secondary / secondary special,Civil marriage
12,274500.0,Unaccompanied,Commercial associate,Secondary / secondary special,Married
13,450000.0,Unaccompanied,Working,Secondary / secondary special,Married
14,229500.0,Family,Working,Secondary / secondary special,Married

In [26]:
# filtering by name
data.loc[10:15, ['NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS']]

              NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS
10  Secondary / secondary special  Single / not married
11  Secondary / secondary special        Civil marriage
12  Secondary / secondary special               Married
13  Secondary / secondary special               Married
14  Secondary / secondary special               Married
15  Secondary / secondary special  Single / not married

In [27]:
# filter rows by condition
data[data['OWN_CAR_AGE'].notnull()].shape

(27316, 197)

In [28]:
# filter rows by multiple conditions
data[data['OWN_CAR_AGE'].notnull() & data['TARGET'] != 0].shape

(1987, 197)

In [29]:
n_bads = len(data[data['TARGET'] == 1])
last_target_on = data[data['TARGET'] == 1]['TIME'].max()

print(f'Number of targets:   {n_bads}')
print(f'Last target on:      {last_target_on}')

Number of targets:   6416
Last target on:      2018-12-31 00:00:00

#### Select columns

In [ ]:
# select columns - result is pd.DataFrame
data[['TIME']]

In [ ]:
type(data[['TIME']])

In [ ]:
# select columns - result is pd.Series
data['TIME']

In [ ]:
type(data['TIME'])

#### Values in columns

In [ ]:
data['NAME_EDUCATION_TYPE'].value_counts(
    dropna = False,
#     normalize = True,
    sort = True,
    ascending = True
)

In [ ]:
data[['MONTH']].drop_duplicates(keep='first')

In [ ]:
data['NAME_CONTRACT_TYPE'].unique()

### Group by

In [ ]:
dt_grp = data.groupby('MONTH').agg({
    'DAY': 'max',
    'TARGET': ['sum', len]
})

dt_grp

In [ ]:
dt_grp = data.groupby('MONTH').agg(
    bad_cnt = ('TARGET', 'sum'),
    tot_cnt = ('TARGET', 'count')
)

dt_grp

### Sort DataFrame

In [ ]:
dt_grp['def_rate'] = dt_grp['bad_cnt'] / dt_grp['tot_cnt']
dt_grp.sort_values('def_rate', ascending = False)

### Joining data frames

#### Join (using index)

In [ ]:
df1 = pd.DataFrame(
    {
        'a': [1,2,3,4],
        'b': [11,12,13,14]
    },
    index = [1,2,3,4]
)

display(df1)

In [ ]:
df2 = pd.DataFrame(
    {
        'a': [2,3,4,5],
        'c': [-2,-3,-4,-5]
    },
    index = [0,2,4,6]
)

display(df2)

In [ ]:
df_joined = df1.join(df2, how = 'inner', lsuffix = '_x', rsuffix = '_y')
df_joined

#### Merge (using column)

In [ ]:
df_joined = df1.merge(df2, on = ['a'], how = 'left')
df_joined

In [ ]:
df_joined.set_index('a', inplace = True)
df_joined

<span style="color:red">**TO DO:** Calculate target rate for Cash loans and revolving loans by months and join results to one dataframe.</span>

1. Filter data NAME_CONTRACT_TYPE = 'Cash loans', group by over months and calculate target rate
2. Filter data NAME_CONTRACT_TYPE = 'Revolving loans', group by over months and calculate target rate
3. join grouped data to one dataframe

### binning

In [ ]:
score_bins = [
    0.0, 0.2, 0.4, 0.6, 0.8, 1.0
]

data['score_binned'] = pd.cut(data['EXT_SOURCE_1'], score_bins, include_lowest=True)
data['score_binned'].value_counts(dropna=False)

<span style="color:red">**TO DO:** Bin `EXT_SOURCE_1` by deciles (or ten equidistant bins). Group by and compute default rate.</span>

**Hint:**
- Use quantile method on pd.Series

### pivoting

In [ ]:
# group by NAME_CONTRACT_TYPE and CODE_GENDER and compute target rates
dt_grp = data.groupby(['NAME_CONTRACT_TYPE', 'CODE_GENDER']).agg(
    cltp_cnt = ('CODE_GENDER', len),
    bad_cnt = ('TARGET', 'sum'),
    tot_cnt = ('TARGET', len)
)
dt_grp['target_rate'] = dt_grp['bad_cnt'] / dt_grp['tot_cnt']

dt_grp.reset_index(inplace=True)
dt_grp

In [ ]:
# pivot table
dt_grp.pivot(index='NAME_CONTRACT_TYPE', columns='CODE_GENDER', values='target_rate')

In [ ]:
# groupby on 3 columns
dt_grp = data.groupby(['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR']).agg(
    cltp_cnt = ('CODE_GENDER', len),
    bad_cnt = ('TARGET', 'sum'),
    tot_cnt = ('TARGET', len)
)
dt_grp['def_rate'] = dt_grp['bad_cnt'] / dt_grp['tot_cnt']

dt_grp.reset_index(inplace=True)
dt_grp

In [ ]:
# pivot with aggfuncs
dt_grp_pivot = dt_grp.pivot_table(index='NAME_CONTRACT_TYPE', columns='CODE_GENDER', values='def_rate', aggfunc = 'mean')
dt_grp_pivot

### unpivoting

In [ ]:
# unpivot data
dt_grp_pivot.reset_index(inplace = True)
dt_grp_pivot.melt(
    id_vars=['NAME_CONTRACT_TYPE'], 
    value_vars=['F', 'M', 'XNA'], 
    var_name='CODE_GENDER', 
    value_name='def_rt'
)

### Few more tricks

In [ ]:
# histogram
data['EXT_SOURCE_1'].hist()

In [ ]:
# histogram with log
data['CNT_CHILDREN'].hist()

# try using log
# data['CNT_CHILDREN'].hist(log=True)

In [ ]:
# correlation
data[['EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3']].corr()

In [ ]:
# get quantile
data['EXT_SOURCE_1'].quantile([0.25, 0.75])

In [ ]:
# crosstab
pd.crosstab(data['FLAG_OWN_CAR'], data['FLAG_OWN_REALTY'])

## Numpy
- numpy provides (beside others) matrix operations

In [ ]:
A = np.array([[1, 2], [2, 3]])
B = np.array([[0, 1], [-1, 2]])

In [ ]:
A

In [ ]:
B

### Matrix multiplication

In [ ]:
# matrix multiplication (np.dot)
np.dot(A, B)

### Element vise multiplication

In [ ]:
# element wise multiplication
A*B

### working with infinity

In [ ]:
# numpy infinity
x = np.inf

In [ ]:
x * 5, x * 0, x / x, -x

### where condition
- similar to excel IF function

In [ ]:
# where condition
data['is_male'] = np.where(data['CODE_GENDER'] == 'M', 1, 0)
data['is_male'].value_counts()

### Solve system of linear equations
If we want to solve a system of linear equations:
$$
a*1 + b*2 = 5
$$
$$
a*3 + b*4 = 11
$$
we can use linaer algebra.

$$
\left[
\begin{array}{cc|c}
1 & 2 & 5 \\
3 & 4 & 11 \\
\end{array}
\right]
\sim
\left[
\begin{array}{cc|c}
1 & 2 & 5 \\
0 & -2 & -4 \\
\end{array}
\right]
\sim
\left[
\begin{array}{cc|c}
1 & 2 & 5 \\
0 & 1 & 2 \\
\end{array}
\right]
\Rightarrow b = 2, a = 1
$$

This functionality is implemented in `numpy.linalg.solve`.

In [ ]:
X = [
    [1,2],
    [3,4]
]

y = [5,11]

a, b = np.linalg.solve(X, y)

print(f'a = {a}')
print(f'b = {b}')

# Graphical outputs
Instruments for grafical outpus are in `matplotlib` library. Another library is `seaborn` - library for statistical data visualization

- Basic plots (scatter plot, line plot, bar chart, box plot, pie chart, histogram)
- Secondary axis
- subplots
- 3D

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

## Histogram

In [ ]:
plt.hist(data['EXT_SOURCE_1'])
plt.show()

In [ ]:
score = 'EXT_SOURCE_1'

plt.hist(
    data['EXT_SOURCE_1'], 
    bins = 25, 
    rwidth = 0.8,
    density = True,
#     cumulative = True,
#     orientation='horizontal'
)
plt.xlabel('score')
plt.ylabel('density')
plt.title(f'Histogram of {score}')


plt.show()

In [ ]:
sns.kdeplot(data=data[data['EXT_SOURCE_1'].notnull()], x="EXT_SOURCE_1")

## Line plot

In [ ]:
dt_grp = data.groupby('MONTH').agg(
    bad_cnt = ('TARGET', 'sum'),
    tot_cnt = ('TARGET', len),
    avg_childern_cnt = ('CNT_CHILDREN', 'mean')
)

dt_grp['target_rate'] = dt_grp['bad_cnt'] / dt_grp['tot_cnt']
dt_grp.reset_index(inplace = True)

In [ ]:
plt.plot(dt_grp['target_rate'])
plt.xticks(range(len(dt_grp)), dt_grp['MONTH'], rotation = 45)

plt.show()

In [ ]:
plt.plot(
    range(len(dt_grp)),
    dt_grp['target_rate'],
    ls = '--',
    marker = 'o',
    label = 'target_rate'
)

plt.plot(
    range(len(dt_grp)),
    dt_grp['avg_childern_cnt'],
    ls = '-.',
    marker = 'o',
    label = 'average childern count',
    color = 'red'
)

plt.xticks(range(len(dt_grp)), dt_grp['MONTH'], rotation = 45)

plt.xlabel('process')
plt.ylabel('default rate')
plt.legend(loc = 'upper right')

plt.show()

## Scatter plot

In [ ]:
plt.scatter(
    data[data['TARGET'] == 0]['EXT_SOURCE_1'], 
    data[data['TARGET'] == 0]['EXT_SOURCE_2'], 
    s = 2,
    color = 'blue',
    label = 'goods'
)

plt.scatter(
    data[data['TARGET'] == 1]['EXT_SOURCE_1'], 
    data[data['TARGET'] == 1]['EXT_SOURCE_2'], 
    s = 5,
    color = 'red',
    label = 'bads'
)

plt.xlabel('SEM_Besc_Score')
plt.ylabel('SEM_TMB_Score')
plt.legend(loc='lower right')

plt.show()

## Box plot

In [ ]:
data[['EXT_SOURCE_1','EXT_SOURCE_2', 'EXT_SOURCE_3']].boxplot(column = ['EXT_SOURCE_1', 'EXT_SOURCE_2'])
plt.show()

In [ ]:
plt.boxplot([
    data[data['EXT_SOURCE_1'].notnull()]['EXT_SOURCE_1'], 
    data[data['EXT_SOURCE_2'].notnull()]['EXT_SOURCE_2']], 
    labels = ['EXT_SOURCE_1','EXT_SOURCE_2'],
    widths = 0.4
)
plt.show()

## Bar chart

In [ ]:
plt.bar(dt_grp.index, dt_grp['bad_cnt'], color = 'red', label = 'bad_cnt')
plt.bar(dt_grp.index, dt_grp['tot_cnt'] - dt_grp['bad_cnt'], bottom = dt_grp['bad_cnt'], color = 'blue', label = 'good_cnt')
plt.xticks(dt_grp.index, dt_grp['MONTH'], rotation = 45)

plt.ylabel('count')
plt.xlabel('process')

plt.show()

## Pie chart

In [ ]:
fig = plt.figure(figsize = (7,7))

plt.pie(dt_grp['tot_cnt'],labels=dt_grp['MONTH'], autopct='%1.1f%%', shadow=False, startangle = 0)
plt.show()

## Dual axis

In [ ]:
ax1 = plt.subplot(111)

ax1.bar(dt_grp.index, dt_grp['bad_cnt'], color = 'coral', label = 'bad_cnt')
ax1.bar(dt_grp.index, dt_grp['tot_cnt'] - dt_grp['bad_cnt'], bottom = dt_grp['bad_cnt'], color = 'lightblue', label = 'good_cnt')
plt.xticks(dt_grp.index, dt_grp['MONTH'], rotation = 45)
ax1.set_ylabel('count')
ax1.set_xlabel('MONTH')

plt.legend(loc='upper right')
ax2 = ax1.twinx()

ax2.plot(
    range(len(dt_grp)),
    dt_grp['target_rate'],
    ls = '-.',
    marker = 'o',
    label = 'target rate',
    color = 'red'
)

ax2.set_ylabel('default rate')
plt.show()

## Subplots

In [ ]:
fig, axs = plt.subplots(2,2, figsize = (12,10))

axs[0,0].plot(
    range(len(dt_grp)),
    dt_grp['target_rate'],
    ls = '--',
    marker = 'o',
    label = 'target rate'
)

axs[0,0].plot(
    range(len(dt_grp)),
    dt_grp['avg_childern_cnt'],
    ls = '-.',
    marker = 'o',
    label = 'average childern count',
    color = 'red'
)

# plt.xticks(range(len(dt_grp)), dt_grp['Process'], rotation = 45)

axs[0,0].set_xlabel('MONTH')
axs[0,0].set_ylabel('target rate')
axs[0,0].legend(loc = 'upper right')

axs[1,0].bar(dt_grp.index, dt_grp['bad_cnt'], color = 'red', label = 'bad_cnt')
axs[1,0].bar(dt_grp.index, dt_grp['tot_cnt'] - dt_grp['bad_cnt'], bottom = dt_grp['bad_cnt'], color = 'blue', label = 'good_cnt')
axs[1,0].set_xticks(range(len(dt_grp)))
# axs[1,0].set_xticks(dt_grp.index)
axs[1,0].set_xticklabels(dt_grp['MONTH'], rotation = 45)

axs[0,1].pie(dt_grp['tot_cnt'],labels=dt_grp['MONTH'], autopct='%1.1f%%', shadow=False, startangle = 0)

axs[1,1].scatter(
    data[data['TARGET'] == 0]['EXT_SOURCE_1'], 
    data[data['TARGET'] == 0]['EXT_SOURCE_2'], 
    s = 2,
    color = 'blue',
    label = 'goods'
)

axs[1,1].scatter(
    data[data['TARGET'] == 1]['EXT_SOURCE_1'], 
    data[data['TARGET'] == 1]['EXT_SOURCE_2'], 
    s = 10,
    color = 'red',
    label = 'bads'
)

axs[1,1].set_xlabel('EXT_SOURCE_1')
axs[1,1].set_ylabel('EXT_SOURCE_2')
axs[1,1].legend(loc='lower right')

plt.show()

<span style="color:red">**TO DO:** Try to create following chart. </span>

Equation for the heart is:
$$x = {\rm{sin}}(t) \cdot {\rm{cos}}(t) \cdot {\rm{ln}\left(\lvert t \rvert\right)}$$
$$y = \sqrt{\lvert t \rvert} \cdot {\rm{cos}}(t)$$
$$t \in [-1,1]$$

<img src="heart.jpg" width=400px style="float: left"/>

## 3D graphs

In [ ]:
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter

fig = plt.figure(figsize=(13,10))
ax = fig.add_subplot(projection = '3d')

# Make data.
X = np.arange(-5, 5, 0.25)
Y = np.arange(-5, 5, 0.25)
X, Y = np.meshgrid(X, Y)
R = np.sqrt(X**2 + Y**2)
Z = np.cos(R)

# Plot the surface.
surf = ax.plot_surface(
    X, Y, Z, 
    cmap=cm.seismic,
    linewidth=0, 
    antialiased=True,
    alpha = 1
)

# Add a color bar which maps values to colors.
fig.colorbar(surf, shrink=0.5, aspect=5)

plt.show()

In [ ]:
target = 'TARGET'
dt = data[(data['EXT_SOURCE_1'].notnull()) & (data['EXT_SOURCE_2'].notnull())][['EXT_SOURCE_1', 'EXT_SOURCE_2', target]]


dt['sc1_bin'] = pd.cut(
    dt['EXT_SOURCE_1'], 
    np.percentile(dt['EXT_SOURCE_1'], range(0, 101, 10)), 
    include_lowest = True,
    labels = False
)

dt['sc2_bin'] = pd.cut(
    dt['EXT_SOURCE_2'], 
    np.percentile(dt['EXT_SOURCE_2'], range(0, 101, 10)), 
    include_lowest = True,
    labels = False
)

dt_grp = dt.groupby(['sc1_bin', 'sc2_bin']).agg(
    target_rate = (target, 'mean'),
)

In [ ]:
dt_grp.reset_index(inplace = True)
dt_grp = dt_grp.sort_values(['sc1_bin', 'sc2_bin'])

In [ ]:
dt_grp_pivot = dt_grp.pivot(index = 'sc1_bin', columns = 'sc2_bin', values = 'target_rate')

X = dt_grp_pivot.index.astype(str)
Y = list(dt_grp_pivot.columns)
X, Y = np.meshgrid(X, Y)
X = X.astype(int)
Y = Y.astype(int)

In [ ]:
fig = plt.figure(figsize=(13,10))
ax = fig.add_subplot(projection = '3d')

surf = ax.plot_wireframe(
        X, Y, dt_grp_pivot.values, 
        antialiased=True,
        alpha = 1
    )

ax.view_init(10, 45)
ax.set_xlabel('ext_score_1')
ax.set_ylabel('ext_score_2')
ax.set_zlabel('target rate')

## Solutions

### Time to datetime

In [ ]:
# data['TIME'].loc[0:5]

# print(data['TIME'].dtype)
# print(type(data['TIME'][0]))
# data['TIME'] = pd.to_datetime(data['TIME'], format='%Y-%m-%d')
# print(data['TIME'].dtype)
# print(type(data['TIME'][0]))

### Target rate for Cash loans and revolving loans by months

In [ ]:
# dt_grp_ex = data[data['NAME_CONTRACT_TYPE'] == 'Cash loans'].groupby('MONTH').agg(
#     dr = ('TARGET', np.mean)
# )

# dt_grp_new = data[data['NAME_CONTRACT_TYPE'] == 'Revolving loans'].groupby('MONTH').agg(
#     dr = ('TARGET', np.mean)
# )

# dt_grp_ex.join(dt_grp_new, lsuffix = '_cl', rsuffix = '_revolving')

### Bin EXT_SOURCE_1 by deciles

In [ ]:
# borders = list(data['EXT_SOURCE_1'].quantile([i/10 for i in range(11)]).values)

# data['sc_bin'] = pd.cut(data['EXT_SOURCE_1'], bins = borders)

# dt_grp = data.groupby('sc_bin').agg(
#     dr = ('TARGET', np.mean)
# )

# dt_grp = dt_grp.sort_index()
# dt_grp

### Heart

In [ ]:
# t = np.arange(-1,1,0.0001)
# x = np.sin(t) * np.cos(t) * np.log(np.abs(t))
# y = np.sqrt(np.abs(t)) * np.cos(t)


# ax1 = plt.subplot(111)
# ax1.bar(np.arange(-0.3, 0.3, 0.06), range(10), width=0.05, alpha=0.2, color='green', edgecolor='blue')

# ax2 = ax1.twinx()

# ax2.plot(x,y, color='red')

# ax1.spines['right'].set_visible(False)
# ax1.spines['top'].set_visible(False)
# ax2.spines['right'].set_visible(False)
# ax2.spines['top'].set_visible(False)


# ax1.spines['left'].set_color('gray')
# ax1.spines['bottom'].set_color('gray')
# ax2.spines['left'].set_color('gray')
# ax2.spines['bottom'].set_color('gray')
# ax1.tick_params(axis='x', colors='gray')
# ax1.tick_params(axis='y', colors='gray')
# ax2.tick_params(axis='y', colors='white')

# plt.savefig('heart.jpg')
# plt.show()